### ISSUE TITLE
MishangUC can't be loaded correctly

### ISSUE THREAD

**Issue by Jeyzhen** [Sinytra/Connector#1102]
### Mod Name

MishangUC

### Mod Homepage

https://github.com/SolidBlock-cn/mishanguc

### Minecraft version

1.20.1

### Describe the bug

net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'mishanguc'!

### Steps to reproduce

Just launch the server and it will crash this log

### Logs

[22:06:03] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'mishanguc'!         at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.43+1.20.1-mod.jar%23134!/:1.0.0-beta.43+1.20.1] {re:mixin,re:classloading}         at net.minecraft.server.Main.handler$zim000$connectormod$earlyInit(Main.java:515) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}         at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}         at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}         at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}         at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}         at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}         at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}         at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}         at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {} Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mishanguc'!         at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:133) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.43+1.20.1-mod.jar%23134!/:1.0.0-beta.43+1.20.1] {re:mixin,re:classloading}         ... 17 more         Suppressed: java.lang.NoClassDefFoundError: Could not initialize class pers.solid.mishang.uc.item.MishangucItems                 at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}                 at jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155) ~[?:?] {}                 at jdk.internal.reflect.UnsafeFieldAccessorFactory.newFieldAccessor(UnsafeFieldAccessorFactory.java:42) ~[?:?] {}                 at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(ReflectionFactory.java:185) ~[?:?] {}                 at java.lang.reflect.Field.acquireFieldAccessor(Field.java:1132) ~[?:?] {}                 at java.lang.reflect.Field.getFieldAccessor(Field.java:1113) ~[?:?] {}                 at java.lang.reflect.Field.get(Field.java:425) ~[?:?] {}                 at pers.solid.mishang.uc.MishangUtils.lambda$instanceEntryStream$4(MishangUtils.java:263) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?] {}                 at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}                 at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?] {}                 at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?] {}                 at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?] {}                 at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}                 at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}                 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}                 at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}                 at pers.solid.mishang.uc.MishangUtils.itemsInternal(MishangUtils.java:214) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%2374!/:?] {}                 at pers.solid.mishang.uc.MishangUtils.items(MishangUtils.java:239) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at pers.solid.mishang.uc.arrp.ARRPMain.generateResources(ARRPMain.java:670) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at pers.solid.mishang.uc.arrp.ARRPMain.onInitialize(ARRPMain.java:849) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}                 at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.43+1.20.1-mod.jar%23134!/:1.0.0-beta.43+1.20.1] {re:mixin,re:classloading}                 at net.minecraft.server.Main.handler$zim000$connectormod$earlyInit(Main.java:515) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}                 at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23165!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}                 at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}                 at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}                 at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}                 at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}                 at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}                 at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.32.jar%2369!/:?] {}                 at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}                 at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}         Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchFieldError: clientTempMemory [in thread "main"]                 at pers.solid.mishang.uc.item.ColumnBuildingTool.<clinit>(ColumnBuildingTool.java:54) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at pers.solid.mishang.uc.item.MishangucItems.<clinit>(MishangucItems.java:30) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 at pers.solid.mishang.uc.Mishanguc.onInitialize(Mishanguc.java:546) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}                 ... 19 more Caused by: java.lang.NoSuchFieldError: clientTempMemory         at pers.solid.mishang.uc.item.ColumnBuildingTool.<clinit>(ColumnBuildingTool.java:54) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}         at pers.solid.mishang.uc.item.MishangucItems.<clinit>(MishangucItems.java:30) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}         at pers.solid.mishang.uc.Mishanguc.onInitialize(Mishanguc.java:546) ~[mishanguc-1.2.5-1.20.1_mapped_srg_1.20.1.jar%23345!/:?] {re:classloading}         at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.43+1.20.1.jar%23130!/:1.0.0-beta.43+1.20.1] {}         at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.43+1.20.1-mod.jar%23134!/:1.0.0-beta.43+1.20.1] {re:mixin,re:classloading}         ... 17 more

### Additional context

Maybe the BRRP mod

**Comment by Su5eD** [comment]
Confirmed to work on Connector beta 43, Forge 47.1.3 server

Mod versions `mishanguc-1.3.0-1.20.1` and `brrp-fabric-1.0.1-1.20.1`

![image](https://github.com/Sinytra/Connector/assets/51261569/6b83b657-57d1-44b0-a2be-de6a185d7307)
