### ISSUE TITLE
Crash with owo-sentinel/numismatic overhaul

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#132]
### Mod Name

numismatic overhaul

### Mod Homepage

https://legacy.curseforge.com/minecraft/mc-mods/numismatic-overhaul

### Describe the bug

crash on boot

### Steps to reproduce

1. install mods
2. install numismatic overhaul
3. watch crash go brrr
...

### Logs

https://gist.github.com/Xplodin/d6af5ec41ce05b523c5f13f9b3ce4aaf

### Additional context

[o?o-sentinel/]: Error thrown while opening sentinel! Exiting
java.lang.UnsupportedOperationException: null
	at net.fabricmc.loader.impl.ModContainerImpl.getContainingMod(ModContainerImpl.java:81) ~[Connector-1.0.0-beta.9+1.20.1-full.jar%23688!/:1.0.0-beta.9+1.20.1]
	at java.util.Optional.flatMap(Optional.java:289) ~[?:?]
	at io.wispforest.owosentinel.OwoSentinel.listOwoDependents(OwoSentinel.java:69) ~[numismatic-overhaul-0.2.10+1.20$owo-sentinel-0.11.0+1.20_mapped_srg_1.20.1.jar%232041!/:?]
	at io.wispforest.owosentinel.SentinelWindow.open(SentinelWindow.java:61) ~[numismatic-overhaul-0.2.10+1.20$owo-sentinel-0.11.0+1.20_mapped_srg_1.20.1.jar%232041!/:?]
	at io.wispforest.owosentinel.OwoSentinel.launch(OwoSentinel.java:45) ~[numismatic-overhaul-0.2.10+1.20$owo-sentinel-0.11.0+1.20_mapped_srg_1.20.1.jar%232041!/:?]
	at io.wispforest.owosentinel.Maldenhagen.<clinit>(Maldenhagen.java:13) ~[numismatic-overhaul-0.2.10+1.20$owo-sentinel-0.11.0+1.20_mapped_srg_1.20.1.jar%232041!/:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:210) ~[Connector-1.0.0-beta.9+1.20.1-full.jar%23688!/:1.0.0-beta.9+1.20.1]
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:195) ~[Connector-1.0.0-beta.9+1.20.1-full.jar%23688!/:1.0.0-beta.9+1.20.1]
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.setup(ConnectorEarlyLoader.java:99) ~[Connector-1.0.0-beta.9+1.20.1-full.jar%23688!/:1.0.0-beta.9+1.20.1]
	at dev.su5ed.sinytra.connector.service.ConnectorPreLaunchPlugin.initializeLaunch(ConnectorPreLaunchPlugin.java:25) ~[Connector-1.0.0-beta.9+1.20.1-full.jar%23688!/:1.0.0-beta.9+1.20.1]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(LaunchPluginHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:51) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by tharrmeehan** [comment]
I believe this has been fixed as of beta 11.

**Comment by Su5eD** [comment]
Indeed, I tested it on beta 11 and it runs fine.
