### ISSUE TITLE
Whats?

### ISSUE THREAD

**Issue by ReyzerMC** [Sinytra/Connector#1391]
---- Minecraft Crash Report ----
// Embeddium instance tainted by mods: [oculus]
// Please do not reach out for Embeddium support without removing these mods first.
// -------
// Don't do that.

Time: 2024-09-04 13:04:09
Description: Rendering overlay

java.lang.ExceptionInInitializerError: null
	at me.srrapero720.embeddiumplus.foundation.fastmodels.FastModels.canUseOnChests(FastModels.java:15) ~[embeddiumplus-1.20.1-v1.2.13.jar%23223!/:1.2.13] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.ChestBlock.handler$zhg001$embeddiumplus$inject$replaceRenderShape(ChestBlock.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:fastmodels.ChestsMixin from mod embeddiumplus,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.ChestBlock.m_7514_(ChestBlock.java) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:fastmodels.ChestsMixin from mod embeddiumplus,pl:mixin:A,pl:connector_pre_launch:A}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60799_(BlockBehaviour.java:605) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
	at net.minecraft.client.resources.model.ModelBakery.m_283980_(ModelBakery.java:361) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] {re:mixin}
	at net.minecraft.client.resources.model.ModelBakery.m_119362_(ModelBakery.java:356) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119341_(ModelBakery.java:243) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119306_(ModelBakery.java:384) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelBakery.m_119263_(ModelBakery.java:143) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.1-jre.jar%23109!/:?] {re:mixin}
	at net.minecraft.client.resources.model.ModelBakery.<init>(ModelBakery.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:puzzleslib.forge.mixins.json:client.accessor.ModelBakeryAccessor from mod puzzleslib,pl:mixin:APP:embeddium.mixins.json:features.model.ModelBakeryMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.resources.model.ModelManager.m_246505_(ModelManager.java:83) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:puzzleslib.forge.mixins.json:client.ModelManagerForgeMixin from mod puzzleslib,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
Caused by: java.lang.RuntimeException: Where is minecraft???!
	at net.minecraftforge.fml.ModLoadingContext.lambda$getActiveContainer$0(ModLoadingContext.java:37) ~[fmlcore-1.20.1-47.3.0.jar%23253!/:?] {}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.ModLoadingContext.getActiveContainer(ModLoadingContext.java:37) ~[fmlcore-1.20.1-47.3.0.jar%23253!/:?] {}
	at net.minecraftforge.fml.ModLoadingContext.registerConfig(ModLoadingContext.java:100) ~[fmlcore-1.20.1-47.3.0.jar%23253!/:?] {}
	at com.jozufozu.flywheel.config.FlwConfig.<init>(FlwConfig.java:23) ~[flywheel-forge-1.20.1-0.6.11-13.jar%23278!/:0.6.11-13] {re:classloading}
	at com.jozufozu.flywheel.config.FlwConfig.<clinit>(FlwConfig.java:13) ~[flywheel-forge-1.20.1-0.6.11-13.jar%23278!/:0.6.11-13] {re:classloading}
	... 21 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Flywheel (flywheel), Version: 0.6.11-13
		Issue tracker URL: https://github.com/Jozufozu/Flywheel/issues
		at TRANSFORMER/flywheel@0.6.11-13/com.jozufozu.flywheel.config.FlwConfig.<init>(FlwConfig.java:23)

	Embeddium++ (embeddiumplus), Version: 1.2.13
		Issue tracker URL: https://github.com/SrRapero720/EmbeddiumPlus/issues
		at TRANSFORMER/embeddiumplus@1.2.13/me.srrapero720.embeddiumplus.foundation.fastmodels.FastModels.canUseOnChests(FastModels.java:15)
Stacktrace:
	at me.srrapero720.embeddiumplus.foundation.fastmodels.FastModels.canUseOnChests(FastModels.java:15) ~[embeddiumplus-1.20.1-v1.2.13.jar%23223!/:1.2.13] {re:mixin,re:classloading}
	at net.minecraft.world.level.block.ChestBlock.handler$zhg001$embeddiumplus$inject$replaceRenderShape(ChestBlock.java:530) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:fastmodels.ChestsMixin from mod embeddiumplus,pl:mixin:A,pl:connector_pre_launch:A}
-- Overlay render details --
Details:
	Overlay name: net.minecraftforge.client.loading.ForgeLoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:957) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:embeddiumplus.mixin.json:darkness.GameRendererMixin from mod embeddiumplus,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor from mod create,pl:mixin:APP:create.mixins.json:client.GameRendererMixin from mod create,pl:mixin:APP:embeddium.mixins.json:features.gui.hooks.console.GameRendererMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin from mod pickupnotifier,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin from mod betterthirdperson,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23252!/:?] {re:mixin,pl:accesstransformer:B,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:pickupnotifier.common.mixins.json:client.MinecraftMixin from mod pickupnotifier,pl:mixin:APP:carryon.mixins.json:MinecraftMixin from mod carryon,pl:mixin:APP:embeddiumplus.mixin.json:fps.GpuUsageMixin from mod embeddiumplus,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor from mod flywheel,pl:mixin:APP:betterthirdperson.mixins.json:MinecraftMixin from mod betterthirdperson,pl:mixin:APP:create.mixins.json:client.WindowResizeMixin from mod create,pl:mixin:APP:embeddium.mixins.json:core.render.MinecraftAccessor from mod embeddium,pl:mixin:APP:embeddium.mixins.json:core.MinecraftClientMixin from mod embeddium,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[1.20.1-forge-47.3.0.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: No
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 510738296 bytes (487 MiB) / 1140850688 bytes (1088 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 12th Gen Intel(R) Core(TM) i5-12400F
	Identifier: Intel64 Family 6 Model 151 Stepping 5
	Microarchitecture: Alder Lake
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 6650 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x73ef
	Graphics card #0 versionInfo: DriverVersion=32.0.11037.4004
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 36418.03
	Virtual memory used (MB): 20497.33
	Swap memory total (MB): 3840.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.20.1-forge-47.3.0
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: AMD Radeon RX 6650 XT GL version 4.6.0 Core Profile Context 24.8.1.240822, ATI Technologies Inc.
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: en_us
	CPU: 12x 12th Gen Intel(R) Core(TM) i5-12400F
	Sinytra Connector: 1.0.0-beta.45+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar mixin-transmogrifier TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar connector_loader TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		JustMoreCakes-forge-1.20.1-1.18.1.jar             |Just More Cakes!              |jmc                           |1.18.1              |NONE      |Manifest: NOSIGNATURE
		BetterAnimationsCollection-v8.0.0-1.20.1-Forge.jar|Better Animations Collection  |betteranimationscollection    |8.0.0               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		YungsBetterDungeons-1.20-Forge-4.0.4.jar          |YUNG's Better Dungeons        |betterdungeons                |1.20-Forge-4.0.4    |NONE      |Manifest: NOSIGNATURE
		geckolib-forge-1.20.1-4.4.jar                     |GeckoLib 4                    |geckolib                      |4.4.2               |NONE      |Manifest: NOSIGNATURE
		common-networking-forge-1.0.5-1.20.1.jar          |Common Networking             |commonnetworking              |1.0.5-1.20.1        |NONE      |Manifest: NOSIGNATURE
		YungsBetterOceanMonuments-1.20-Forge-3.0.4.jar    |YUNG's Better Ocean Monuments |betteroceanmonuments          |1.20-Forge-3.0.4    |NONE      |Manifest: NOSIGNATURE
		goblintraders-forge-1.20.1-1.9.3.jar              |Goblin Traders                |goblintraders                 |1.9.3               |NONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		rustic_engineer-1.20.1-1.0.7.jar                  |Rustic Engineer               |rustic_engineer               |1.0.0               |NONE      |Manifest: NOSIGNATURE
		journeymap-1.20.1-5.10.2-forge.jar                |Journeymap                    |journeymap                    |5.10.2              |NONE      |Manifest: NOSIGNATURE
		citadel-2.6.0-1.20.1.jar                          |Citadel                       |citadel                       |2.6.0               |NONE      |Manifest: NOSIGNATURE
		alexsmobs-1.22.8.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.8              |NONE      |Manifest: NOSIGNATURE
		travelersbackpack-forge-1.20.1-9.1.15.jar         |Traveler's Backpack           |travelersbackpack             |9.1.15              |NONE      |Manifest: NOSIGNATURE
		YungsApi-1.20-Forge-4.0.5.jar                     |YUNG's API                    |yungsapi                      |1.20-Forge-4.0.5    |NONE      |Manifest: NOSIGNATURE
		mixinextras-forge-0.3.6.jar                       |MixinExtras                   |mixinextras                   |0.3.6               |NONE      |Manifest: NOSIGNATURE
		PickUpNotifier-v8.0.0-1.20.1-Forge.jar            |Pick Up Notifier              |pickupnotifier                |8.0.0               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |NONE      |Manifest: NOSIGNATURE
		puzzlesaccessapi-forge-8.0.7.jar                  |Puzzles Access Api            |puzzlesaccessapi              |8.0.7               |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		YungsBetterNetherFortresses-1.20-Forge-2.0.6.jar  |YUNG's Better Nether Fortresse|betterfortresses              |1.20-Forge-2.0.6    |NONE      |Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |NONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		embeddium-0.3.31+mc1.20.1.jar                     |Embeddium                     |embeddium                     |0.3.31+mc1.20.1     |NONE      |Manifest: NOSIGNATURE
		embeddiumplus-1.20.1-v1.2.13.jar                  |Embeddium++                   |embeddiumplus                 |1.2.13              |NONE      |Manifest: NOSIGNATURE
		friendsandfoes-forge-mc1.20.1-2.0.16.jar          |Friends&Foes                  |friendsandfoes                |2.0.16              |NONE      |Manifest: NOSIGNATURE
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |NONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		music_dimension-1.0.2-forge-1.20.1.jar            |Music Dimension               |music_dimension               |1.0.2               |NONE      |Manifest: NOSIGNATURE
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |NONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.20.1-3.0.1.7.jar             |TerraBlender                  |terrablender                  |3.0.1.7             |NONE      |Manifest: NOSIGNATURE
		RegionsUnexploredForge-0.5.6+1.20.1.jar           |Regions Unexplored            |regions_unexplored            |0.5.6               |NONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.20.1-18.0.0.592.jar               |Biomes O' Plenty              |biomesoplenty                 |18.0.0.592          |NONE      |Manifest: NOSIGNATURE
		Amplified_Nether_1.20.x_v1.2.5.jar                |Amplified Nether              |amplified_nether              |1.2.5               |NONE      |Manifest: NOSIGNATURE
		flywheel-forge-1.20.1-0.6.11-13.jar               |Flywheel                      |flywheel                      |0.6.11-13           |NONE      |Manifest: NOSIGNATURE
		create-1.20.1-0.5.1.h.jar                         |Create                        |create                        |0.5.1.h             |NONE      |Manifest: NOSIGNATURE
		SpartanShields-1.20.1-forge-3.1.1.jar             |Spartan Shields               |spartanshields                |3.1.1               |NONE      |Manifest: NOSIGNATURE
		right-click-harvest-3.2.3+1.20.1-forge.jar        |Right Click Harvest           |rightclickharvest             |3.2.3+1.20.1-forge  |NONE      |Manifest: NOSIGNATURE
		oculus-mc1.20.1-1.7.0.jar                         |Oculus                        |oculus                        |1.7.0               |NONE      |Manifest: NOSIGNATURE
		crittersandcompanions-1.20.1-2.1.6.jar            |Critters and Companions       |crittersandcompanions         |1.20.1-2.1.6        |NONE      |Manifest: NOSIGNATURE
		BetterThirdPerson-Forge-1.20-1.9.0.jar            |Better Third Person           |betterthirdperson             |1.9.0               |NONE      |Manifest: NOSIGNATURE
		inventoryhud.forge.1.20.1-3.4.26.jar              |Inventory HUD+                |inventoryhud                  |3.4.26              |NONE      |Manifest: NOSIGNATURE
		Connector-1.0.0-beta.45+1.20.1-mod.jar            |Connector                     |connectormod                  |1.0.0-beta.45+1.20.1|NONE      |Manifest: NOSIGNATURE
		YungsBetterStrongholds-1.20-Forge-4.0.3.jar       |YUNG's Better Strongholds     |betterstrongholds             |1.20-Forge-4.0.3    |NONE      |Manifest: NOSIGNATURE
		SpartanWeaponry-1.20.1-forge-3.1.3-all.jar        |Spartan Weaponry              |spartanweaponry               |3.1.3               |NONE      |Manifest: NOSIGNATURE
		mcw-furniture-3.3.0-mc1.20.1forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.3.0               |NONE      |Manifest: NOSIGNATURE
		YungsBetterEndIsland-1.20-Forge-2.0.6.jar         |YUNG's Better End Island      |betterendisland               |1.20-Forge-2.0.6    |NONE      |Manifest: NOSIGNATURE
		PuzzlesLib-v8.1.22-1.20.1-Forge.jar               |Puzzles Lib                   |puzzleslib                    |8.1.22              |NONE      |Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Aquaculture-1.20.1-2.5.2.jar                      |Aquaculture 2                 |aquaculture                   |2.5.2               |NONE      |Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.7.7.jar                  |Framework                     |framework                     |0.7.7               |NONE      |Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		Towns-and-Towers-1.12-Fabric+Forge.jar            |Towns and Towers              |t_and_t                       |0.0NONE             |NONE      |Manifest: NOSIGNATURE
		cristellib-1.1.5-forge.jar                        |Cristel Lib                   |cristellib                    |1.1.5               |NONE      |Manifest: NOSIGNATURE

**Comment by Su5eD** [comment]
Please read the issue template more carefully. For modpack related issues, use the `support` channel on our [discord](https://discord.sinytra.org) server.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

> To upload logs, use an external paste site, such as Github Gist (recommended), Ubuntu Pastebin or Pastebin
