### ISSUE TITLE
Crash with held item info

### ISSUE THREAD

**Issue by lzm11111111** [Sinytra/Connector#1399]
### Mod Name

Held item info

### Mod Homepage

https://modrinth.com/mod/held-item-info

### Minecraft version

1.20.1 (LTS)

### Describe the bug

When the held item info mod have installed, this game will crash at start

### Steps to reproduce

Mod list:
Held item info
Sinytra Connecter
Forgified Farbic API

### Logs

[099月2024 23:16:56.235] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Nicked, --version, 1.20.1-Forge_47.2.18, --gameDir, C:\Users\Administrator\Desktop\Client\.minecraft\versions\1.20.1-Forge_47.2.18, --assetsDir, C:\Users\Administrator\Desktop\Client\.minecraft\assets, --assetIndex, 5, --uuid, 0000000000003006998F555B48C1AB04, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 873, --height, 508, --launchTarget, forgeclient, --fml.forgeVersion, 47.2.18, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412] [099月2024 23:16:56.278] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0 [099月2024 23:16:56.979] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow [099月2024 23:16:57.608] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 [099月2024 23:16:58.690] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6 [099月2024 23:16:58.888] [main/INFO] [mixin-transmog/]: Mixin Transmogrifier is definitely up to no good... [099月2024 23:16:58.983] [main/INFO] [mixin-transmog/]: crimes against java were committed [099月2024 23:16:59.086] [main/INFO] [mixin-transmog/]: Original mixin transformation service successfully crobbed by mixin-transmogrifier! [099月2024 23:16:59.386] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/Administrator/Desktop/Client/.minecraft/versions/1.20.1-Forge_47.2.18/mods/Connector-1.0.0-beta.45+1.20.1.jar%23159%23162!/ Service=ModLauncher Env=CLIENT [099月2024 23:17:00.266] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: AMD Radeon R7 Graphics GL version 4.6.13596 Core Profile Forward-Compatible Context 20.10.20 27.20.1020.1, ATI Technologies Inc. [099月2024 23:17:01.143] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\Client\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.18\fmlcore-1.20.1-47.2.18.jar is missing mods.toml file [099月2024 23:17:01.157] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\Client\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.18\javafmllanguage-1.20.1-47.2.18.jar is missing mods.toml file [099月2024 23:17:01.176] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\Client\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.18\lowcodelanguage-1.20.1-47.2.18.jar is missing mods.toml file [099月2024 23:17:01.201] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\Administrator\Desktop\Client\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.18\mclanguage-1.20.1-47.2.18.jar is missing mods.toml file [099月2024 23:17:02.280] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 47 dependencies adding them to mods collection [099月2024 23:17:02.898] [main/INFO] [org.sinytra.connector.locator.DependencyResolver/]: Dependency resolution found 1 candidates to load [099月2024 23:17:05.376] [main/INFO] [org.sinytra.connector.service.hacks.ModuleLayerMigrator/]: Successfully made module authlib transformable [099月2024 23:17:08.257] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [099月2024 23:17:08.602] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-Forge_47.2.18, --gameDir, C:\Users\Administrator\Desktop\Client\.minecraft\versions\1.20.1-Forge_47.2.18, --assetsDir, C:\Users\Administrator\Desktop\Client\.minecraft\assets, --uuid, 0000000000003006998F555B48C1AB04, --username, Nicked, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 873, --height, 508] [099月2024 23:17:09.375] [main/WARN] [mixin/]: Reference map '' for adapter.init.mixins.json could not be read. If this is a development environment you can ignore this message [099月2024 23:17:13.736] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). [099月2024 23:17:29.908] [Datafixer Bootstrap/INFO] [com.mojang.datafixers.DataFixerBuilder/]: 188 Datafixer optimizations took 1003 milliseconds [099月2024 23:17:35.786] [Client Shutdown Thread/ERROR] [net.minecraft.client.main.Main/]: Caught previously unhandled exception : org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] 	at net.minecraft.client.main.Main$2.run(Main.java:164) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onBeforeRenderHeldItemTooltip(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in held-item-info.mixins.json:HeldItemTooltipMixin from mod held_item_info failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap held-item-info-refmap.json 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	... 14 more

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
