### ISSUE TITLE
[1.21.1] Invisible player body in Flashback replays. Possible coremod conflict between mixins and NeoForge's base coremod system.

### ISSUE THREAD

**Issue by VOLKOUL** [Sinytra/Connector#1452]
### Minecraft version

1.21.1

### Describe the bug

To start off, the second part of the title of this issue is a response I got from the developer of one of the mods this issue affects. The Flashback mod runs fine on Connector, but once certain mods are introduced, the player's body in any replay just ceases to exist, leaving only a flying head. This does not occur on Fabric (tested with the Fabric versions of the mods). The mods causing this (that I have found thus far) are Xaero's Worldmap and Nostalgic Tweaks.
![Image](https://github.com/user-attachments/assets/2a4020f1-1720-42b3-8d13-0fc0308292d8)

### Steps to reproduce

Easiest way:
1. Install Connector, Connector Extras, FFAPI, Flashback and Xaero's Worldmap
2. Record a replay
3. Enter the replay and get spooked

### Additional context

The current officially available version of NostalgicTweaks needs to be edited to launch on 1.21.1 and causes lighting issues with Flashback, but there is a GitHub fork that fixes this, the [link](https://github.com/Xenthio/Nostalgic-Tweaks-X/tree/1.21) to which can be found in the NT's Discord. (since the developer of NT is on a hiatus others started to fix some bugs)

Also I know that this is technically a mod incompatibility issue, but from what I understand the "origin" of the issue is Connector sooo ¯\_(ツ)_/¯

**Comment by Spud-Developer** [comment]
I found that when the player's body is invisible, if you go into spectator mode then back out, then the body reappears??
I think it might have something to do with spectator mode because of this
maybe it doesn't render the body because some problem with neoforge and spectator mode?
no clue.
but strange none the less :P

**Comment by VOLKOUL** [comment]
Your method doesn't seem to work for me, unfortunately. You might be referring to Flashback's "fake" camera-client body that appears when you switch gamemodes in a replay and which has one of Minecraft's default skins. It's not the same as the actual player in the recording.

Also, Flashback versions past 0.13.0 crash the game when trying to enter or create a world. Flashback 0.16.0 for 1.21.1 can be found in Flashback's Discord.

**Comment by VOLKOUL** [comment]
I am currently in the process of finding more mods in my modpack that cause this behavior. **There are a lot of them.** Some even make the entire player disappear, including the head. When this happens, the player seemingly ceases to exist altogether, as Flashback's "spectate player" selection menu is empty. It also spawns the camera in a different location.

**Comment by Spud-Developer** [comment]
Oh, well I wasn't talking about the "Replay Viewer" fake player when seeing
a replay, For me I simply just ran '/gamemode survival @a' then set the
replay viewer back to spectator and all bodies reappeared, though it goes
back to being a head once they die or you go back in the replay, making it
reload everything.
The player ceasing to exist altogether could be from a mod changing how the
game renders or the way the player renders, I'm not sure :3

**Comment by VOLKOUL** [comment]
After what feels like eternity here are all the mods that I found which break Flashback: (there are a few mods included that are dependents of others)

Aether
Backpacked
Carryon
CMDcam
Comforts
Configured
Dummmmmmy
FastFurnace
FastWorkbench
ImmersiveEngineering
Jade
Kiwi
LittleTiles
Mekanism (+addons)
Moonlight
NostalgicTweaks
Placebo
Prone was pressed
SnowRealMagic
Supplementaries
Titanium
TwilightForest
Waystones
XaerosMinimap
XaerosWorldMap

Ur welcome :>

**Comment by VOLKOUL** [comment]
There are some unique cases like Carryon making the entire body (head included) disappear and Mekanism crashing the game when exiting replays. Most mods however only "delete" just the body.

**Comment by wieldless** [comment]
> Also, Flashback versions past 0.13.0 crash the game when trying to enter or create a world. Flashback 0.16.0 for 1.21.1 can be found in Flashback's Discord.

I was also unable to use any version past 0.13.0 (specifically anything past commit 67aa3c1) and tried to find out why it crashed.
Seems like on commit 7c97b9d something called "MixinBiomeModificationImpl" was introduced which is responsible for the crashes.
I made a fork and, when built with it excluded, 0.31.0 seems to work without any glaring issues: https://github.com/wieldless/Flashback-MBMIless/tree/1.21

Maybe an upgraded version could help with preventing Flashback from breaking?

**Comment by VOLKOUL** [comment]
That's awesome! Do you think you can add a ready jar in the releases? (I'll be honest, I am too bored to compile it myself lol)

**Comment by VOLKOUL** [comment]
Also, have you thought of telling the Flashback dev about this? (I mean, they probably know, but still)

**Comment by wieldless** [comment]
> That's awesome! Do you think you can add a ready jar in the releases? (I'll be honest, I am too bored to compile it myself lol)

I dunno if I can do that, no other fork did it so I'm inclined to believe I can't


> Also, have you thought of telling the Flashback dev about this? (I mean, they probably know, but still)

If the README tells the truth of "Flashback currently does not accept outside contributions", then I don't know if I really can. The dev will prolly look at it in their own time, I'll patch the build if there are any changes in the meantime as having Flashback running on NeoForge is what I primarily want out of this

**Comment by wieldless** [comment]
> The Flashback mod runs fine on Connector, but once certain mods are introduced, the player's body in any replay just ceases to exist, leaving only a flying head. This does not occur on Fabric (tested with the Fabric versions of the mods).

I could sadly replicate this issue in my 0.31.0 build, Motion Capture (https://modrinth.com/mod/motion-capture) does erase the player's body as well. A preliminary solution really seems to be to use the Fabric build of any offending mod through Connector so that whatever NeoForge uses that causes this conflict can be avoided. If there isn't a Fabric counterpart and it doesn't work, tough luck for now...

<img src="https://github.com/user-attachments/assets/560d1e33-f668-4ac9-8a9a-7ee3220d2cf4" width=50% height=50% title="Fabric version under Connector"><img src="https://github.com/user-attachments/assets/205881ab-bb57-433f-aa18-e6a574921595" width=50% height=50% title="NeoForge version"> 

> There are some unique cases like Carryon making the entire body (head included) disappear

Could replicate that too, and there again using the Fabric version under Connector fixes it.

<img src="https://github.com/user-attachments/assets/82e714c9-aa37-4bd5-8073-e0190bd0c5d1" width=50% height=50% title="Fabric version under Connector"><img src="https://github.com/user-attachments/assets/b4556853-b601-491e-b480-d124b316ba97" width=50% height=50% title="NeoForge version">

**Comment by adaliszk** [comment]
> If there isn't a Fabric counterpart and it doesn't work, tough luck for now...

Yeah... Nice work with the fork! It seems it does make Flashback mostly work, it just does not record players on my end, so now I'm off the hunt finding which of the 150 mods causes it :D

**Comment by VOLKOUL** [comment]
Try the ones I listed above :D

**Comment by adaliszk** [comment]
I tried, but none helped. One interesting thing is that when I only have a flashback and create, it suddenly does not even load a recording.

**Comment by adaliszk** [comment]
Okay, I found my issue likely to be "Beans Backpacks". However, once added, it fixes the issues with Create, where the root problem is that the recording tries to send payloads to the client meant for the server: `java.lang.UnsupportedOperationException: Payload create:clientbound_chain_conveyor may not be sent to the client!`

Now, the issue with Beans does not seem to be with rendering only, but the entire player list, and the player is not recorded. However, with the mentioned spectator trick, the player list is populated, so at that point, I assume it's only a rendering issue.

**Comment by adaliszk** [comment]
So, after adding a try-catch around the problematic region:
```
        // Tick underlying server
        try {
            super.tickServer(booleanSupplier);
        } catch (UnsupportedOperationException err) {
            // Ignore
        }
```
then I see a floating head with create just fine, which fixes itself once I use the spectator trick.

**Comment by VOLKOUL** [comment]
Where do we put that exactly? I am no coder lmao

**Comment by adaliszk** [comment]
https://github.com/wieldless/Flashback-MBMIless/blob/1.21/src/main/java/com/moulberry/flashback/playback/ReplayServer.java#L1086-L1087

**Comment by wieldless** [comment]
> > If there isn't a Fabric counterpart and it doesn't work, tough luck for now...
> 
> Yeah... Nice work with the fork! It seems it does make Flashback mostly work, it just does not record players on my end, so now I'm off the hunt finding which of the 150 mods causes it :D

I apologize for that being unavoidable for now, but at least it's better that staying at 0.13.0



> So, after adding a try-catch around the problematic region:
> ```...```
> then I see a floating head with create just fine, which fixes itself once I use the spectator trick.

To make it easier for us here, I implemented it into the fork, hope that is fine! Also integrated the changes that Moulberry made for 0.32.0, don't have the time to test that right now though. It seems to be running fine at a glance so that is a relieve at least.
For redundancy - https://github.com/wieldless/Flashback-MBMIless/tree/1.21

**Comment by adaliszk** [comment]
> To make it easier for us here, I implemented it into the fork, and I hope that is fine!

Absolutely. I was thinking of just opening PRs at some point, but I wanted to find out why the player data is not recorded when certain mods are loaded. Understanding it and narrowing it down to possible failing points will take some time.

However, if anyone has clear errors or even a crash while trying to record but has no player data, that could help a lot!

**Comment by Qubik65536** [comment]
I also added another `try-catch`: https://github.com/Qubik65536/Flashback-InvisiblePlayerFix/commit/daf2ab5d334b2f70e386ff16c76334e1003323f1.

This will allow a `serverPlayer.setGameMode(gameType);` following the `placeNewPlayer` to properly run and set the user to the right game mode. By doing so, in my test, the player's body is now properly rendered when:

1. the replay is loaded.
2. the player respawns.

without needing to manually use the `gamemode` command to show the player. If this helps. 

Note: Might still have issues with some mods though if no player data is ever recorded due to incompatibility.

**Comment by Qubik65536** [comment]
> So, after adding a try-catch around the problematic region:
> 
> ```
>         // Tick underlying server
>         try {
>             super.tickServer(booleanSupplier);
>         } catch (UnsupportedOperationException err) {
>             // Ignore
>         }
> ```
> 
> then I see a floating head with create just fine, which fixes itself once I use the spectator trick.

And there are still cases that might crash the game even with the try-catch:

```log
[27Jul2025 19:32:50.571] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1041) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.runUpdates(ReplayServer.java:1133) ~[flashback-0.36.0_mapped_moj_1.21.1.jar%23445!/:?]
	at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.tickServer(ReplayServer.java:913) ~[flashback-0.36.0_mapped_moj_1.21.1.jar%23445!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.UnsupportedOperationException: Payload create:minecart_controller may not be sent to the client!
	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:446) ~[neoforge-21.1.194-universal.jar%23226!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:178) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:173) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:1259) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.broadcast(ChunkMap.java:1157) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.broadcast(ServerChunkCache.java:480) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.network.PacketDistributor.sendToPlayersTrackingEntity(PacketDistributor.java:93) ~[neoforge-21.1.194-universal.jar%23226!/:?]
	at TRANSFORMER/ponder@1.0.56/net.createmod.catnip.platform.NeoForgeNetworkHelper.sendToClientsTrackingEntity(NeoForgeNetworkHelper.java:79) ~[Ponder-NeoForge-1.21.1-1.0.56.jar%23385!/:1.0.56]
	at TRANSFORMER/create@6.0.6/com.simibubi.create.content.contraptions.minecart.capability.MinecartController.sendData(MinecartController.java:318) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
	at TRANSFORMER/create@6.0.6/com.simibubi.create.content.contraptions.minecart.capability.CapabilityMinecartController.startTracking(CapabilityMinecartController.java:205) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
	at TRANSFORMER/create@6.0.6/com.simibubi.create.foundation.events.CommonEvents.startTracking(CommonEvents.java:214) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:360) ~[bus-8.0.5.jar%23159!/:?]
	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:328) ~[bus-8.0.5.jar%23159!/:?]
	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.event.EventHooks.onStartEntityTracking(EventHooks.java:479) ~[neoforge-21.1.194-universal.jar%23226!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:244) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1294) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1321) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1149) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:322) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:379) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
```

I am still trying to debug this but have no idea in which case this might occur.

Edit: Fixed it with https://github.com/Qubik65536/Flashback-InvisiblePlayerFix/commit/99fcac55f727a7595aaccf8e0dd44116d0c4e72b#diff-ddf61bbe1c98285f586f0a5205b8314fe5f653f0d25e1c824e95c32b47e3acb3R1080-R1171, but it will cause a huge lag when it is being handled. The lag is not visible in the rendered video.

**Comment by VOLKOUL** [comment]
What a chad

Does this incorporate wieldless's fix too?

Also do I need to download from the 1.21 branch or the master branch?

**Comment by Qubik65536** [comment]
> What a chad
> 
> Does this incorporate wieldless's fix too?
> 
> Also do I need to download from the 1.21 branch or the master branch?

You will need to download and build from the 1.21 branch and no it doesn’t include @wieldless’s fix. I’ll probably include it in my version once I figured out if it is necessary for my own needs.

**Comment by wieldless** [comment]
> What a chad
> 
> Does this incorporate wieldless's fix too?
> 
> Also do I need to download from the 1.21 branch or the master branch?

It basically does, as the only thing that was left unfixed was what @adaliszk 's try-catch tried to isolate. Excluding MixinBiomeModificationImpl wasn't necessary since 0.32.1, as Moulberry fixed it themselves, which means my fork is obsolete now.

**Comment by Qubik65536** [comment]
> > What a chad
> > Does this incorporate wieldless's fix too?
> > Also do I need to download from the 1.21 branch or the master branch?
> 
> It basically does, as the only thing that was left unfixed was what [@adaliszk](https://github.com/adaliszk) 's try-catch tried to isolate. Excluding MixinBiomeModificationImpl wasn't necessary since 0.32.1, as Moulberry fixed it themselves, which means my fork is obsolete now.

I think those try-catch were also added in another commit. There are three try-catches with the latest commit in the 1.21 branch:

1. UnsupportedOperationException for the tick server (what @adaliszk added).
2. ReportedException wrapping a UnsupportedOperationException for the tick server.
3. UnsupportedOperationException when spawning the user.

**Comment by Qubik65536** [comment]
Do we have any clue about why an `UnsupportedOperationException Payload xxx may not be sent to the client!` might be thrown and how can we really fix it? It seems that sometimes this incompatibility issue does impact the functionality of the conflicted mod and still doesn't allow Flaskback to render the player anyway (even though the try-catch made it not crashing).

**Comment by muddle6969** [comment]
> > So, after adding a try-catch around the problematic region:
> > ```
> >         // Tick underlying server
> >         try {
> >             super.tickServer(booleanSupplier);
> >         } catch (UnsupportedOperationException err) {
> >             // Ignore
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > then I see a floating head with create just fine, which fixes itself once I use the spectator trick.
> 
> And there are still cases that might crash the game even with the try-catch:
> 
> ```
> [27Jul2025 19:32:50.571] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
> net.minecraft.ReportedException: Exception ticking world
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1041) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:917) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.runUpdates(ReplayServer.java:1133) ~[flashback-0.36.0_mapped_moj_1.21.1.jar%23445!/:?]
> 	at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.tickServer(ReplayServer.java:913) ~[flashback-0.36.0_mapped_moj_1.21.1.jar%23445!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
> Caused by: java.lang.UnsupportedOperationException: Payload create:minecart_controller may not be sent to the client!
> 	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:446) ~[neoforge-21.1.194-universal.jar%23226!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:178) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:173) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.broadcast(ChunkMap.java:1259) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.broadcast(ChunkMap.java:1157) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.broadcast(ServerChunkCache.java:480) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.network.PacketDistributor.sendToPlayersTrackingEntity(PacketDistributor.java:93) ~[neoforge-21.1.194-universal.jar%23226!/:?]
> 	at TRANSFORMER/ponder@1.0.56/net.createmod.catnip.platform.NeoForgeNetworkHelper.sendToClientsTrackingEntity(NeoForgeNetworkHelper.java:79) ~[Ponder-NeoForge-1.21.1-1.0.56.jar%23385!/:1.0.56]
> 	at TRANSFORMER/create@6.0.6/com.simibubi.create.content.contraptions.minecart.capability.MinecartController.sendData(MinecartController.java:318) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
> 	at TRANSFORMER/create@6.0.6/com.simibubi.create.content.contraptions.minecart.capability.CapabilityMinecartController.startTracking(CapabilityMinecartController.java:205) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
> 	at TRANSFORMER/create@6.0.6/com.simibubi.create.foundation.events.CommonEvents.startTracking(CommonEvents.java:214) ~[create-1.21.1-6.0.6.jar%23236!/:6.0.6]
> 	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:360) ~[bus-8.0.5.jar%23159!/:?]
> 	at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:328) ~[bus-8.0.5.jar%23159!/:?]
> 	at TRANSFORMER/neoforge@21.1.194/net.neoforged.neoforge.event.EventHooks.onStartEntityTracking(EventHooks.java:479) ~[neoforge-21.1.194-universal.jar%23226!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerEntity.addPairing(ServerEntity.java:244) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayer(ChunkMap.java:1294) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap$TrackedEntity.updatePlayers(ChunkMap.java:1321) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ChunkMap.tick(ChunkMap.java:1149) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:322) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:379) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1037) ~[client-1.21.1-20240808.144430-srg.jar%23225!/:?]
> ```
> 
> I am still trying to debug this but have no idea in which case this might occur.
> 
> Edit: Fixed it with [Qubik65536/Flashback-InvisiblePlayerFix@99fcac5#diff-ddf61bbe1c98285f586f0a5205b8314fe5f653f0d25e1c824e95c32b47e3acb3R1080-R1171](https://github.com/Qubik65536/Flashback-InvisiblePlayerFix/commit/99fcac55f727a7595aaccf8e0dd44116d0c4e72b#diff-ddf61bbe1c98285f586f0a5205b8314fe5f653f0d25e1c824e95c32b47e3acb3R1080-R1171), but it will cause a huge lag when it is being handled. The lag is not visible in the rendered video.

how do i install this. i do have bunch of mods installed. i want to help.

**Comment by VOLKOUL** [comment]
Go here https://github.com/Qubik65536/Flashback-InvisiblePlayerFix/tree/1.21, tap Code, download as zip, extract, open CMD in the folder, type gradlew build and wait. The compiled mod should be in the libs folder. Go watch a tutorial on how to compile mods, you're unlikely to get it right if you're doing this for the first time.

**Comment by muddle6969** [comment]
I installed Quibiks' fix.
World was invisible. even in the replay section i could see the thumbnail.
i removed the mods listed above by VOLKOUL, apart from it curios mod is also problematic for it.
now the replay crashes  as soon as i open it. 


[21:59:59] [Server thread/ERROR] [ne.ne.bu.EventBus/EVENTBUS]:
Exception caught during firing event: Payload shetiphiancore:team_sync may not be sent to the client!

From Line 1256: It was about Create Mod

21:59:59] [Server thread/ERROR] [ne.ne.bu.EventBus/EVENTBUS]: Exception caught during firing event: Payload create:server_speed may not be sent to the client!
--
  | Index: 15
  | Listeners:
  | 0: net.neoforged.bus.EventListenerFactory$event/0x00000289358c2800@1b4e6f0a
  | 1: net.neoforged.bus.EventListenerFactory$postServerTick/0x000002893520d800@35404c0a
  | 2: net.neoforged.bus.EventListenerFactory$onEndTick/0x0000028935254400@3a2fb24d
  | 3: net.neoforged.bus.EventListenerFactory$onServerTick/0x0000028935385400@52835ffd
  | 4: net.neoforged.bus.EventListenerFactory$tick/0x00000289354b4c00@3add5c98
  | 5: net.neoforged.bus.EventListenerFactory$tick/0x0000028935545000@dca67d5
  | 6: net.neoforged.bus.EventListenerFactory$tick/0x0000028935550000@4ab001fb
  | 7: net.neoforged.bus.EventListenerFactory$onServerTick/0x000002893580c400@284d3e7
  | 8: net.neoforged.bus.EventListenerFactory$tick/0x0000028935850c00@526d66b3
  | 9: net.fabricmc.fabric.impl.event.lifecycle.LifecycleEventsImpl$$Lambda/0x0000028935855520@26c26d3a
  | 10: net.neoforged.bus.EventListenerFactory$tick/0x0000028935b19400@cc757e4
  | 11: net.neoforged.bus.EventListenerFactory$tick/0x0000028935b7c000@4632305e
  | 12: net.neoforged.bus.EventListenerFactory$tick/0x0000028935bac000@628dc894
  | 13: net.neoforged.bus.EventListenerFactory$tick/0x0000028935bac400@5bec7288
  | 14: net.neoforged.bus.EventListenerFactory$onServerTick/0x0000028935cf0000@6da26666
  | 15: net.neoforged.bus.EventListenerFactory$onServerTick/0x0000028935fe8000@3ac50b4c
  | java.lang.UnsupportedOperationException: Payload create:server_speed may not be sent to the client!
  | at TRANSFORMER/neoforge@21.1.188/net.neoforged.neoforge.network.registration.NetworkRegistry.checkPacket(NetworkRegistry.java:446)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:178)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerCommonPacketListenerImpl.send(ServerCommonPacketListenerImpl.java:173)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.players.PlayerList.broadcastAll(PlayerList.java:542)
  | at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer$1.broadcastAll(ReplayServer.java:363)
  | at TRANSFORMER/neoforge@21.1.188/net.neoforged.neoforge.network.PacketDistributor.sendToAllPlayers(PacketDistributor.java:83)
  | at TRANSFORMER/ponder@1.0.56/net.createmod.catnip.platform.NeoForgeNetworkHelper.sendToAllClients(NeoForgeNetworkHelper.java:69)
  | at TRANSFORMER/create@6.0.6/com.simibubi.create.foundation.utility.ServerSpeedProvider.serverTick(ServerSpeedProvider.java:27)
  | at TRANSFORMER/create@6.0.6/com.simibubi.create.foundation.events.CommonEvents.onServerTick(CommonEvents.java:98)
  | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:360)
  | at MC-BOOTSTRAP/net.neoforged.bus/net.neoforged.bus.EventBus.post(EventBus.java:328)
  | at TRANSFORMER/neoforge@21.1.188/net.neoforged.neoforge.event.EventHooks.fireServerTickPost(EventHooks.java:1020)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:943)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.server.IntegratedServer.tickServer(IntegratedServer.java:110)
  | at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.runUpdates(ReplayServer.java:1157)
  | at TRANSFORMER/flashback@0.36.0/com.moulberry.flashback.playback.ReplayServer.tickServer(ReplayServer.java:919)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:707)
  | at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:267)
  | at java.base/java.lang.Thread.run(Unknown Source)


Full Crash Log:
https://mclo.gs/HUSlXkV

**Comment by adaliszk** [comment]
Did anybody make an updated version with 0.39 already?

From my current testing, Comforts and Jade loads from the list, as well as Create with Copycats, Metalworks, Power Loader, Vibrant Vaults, Blocks & Bogies. Note that loading does not mean it has no issues; we'll see later.

Key finding, though, is that additional things that do not work are:
- Beans Backpacks
- EMI Loot, EMI Ores
- Distant Horizons 2.4, but 2.3 works
- Watut partially, it does not crash, but it does not record the screens either

**Comment by Su5eD** [comment]
Closing as this works on 26.1.2 now.
