### ISSUE TITLE
Crash on launch with dye depot

### ISSUE THREAD

**Issue by Sky88Dog** [Sinytra/Connector#1459]
### Mod Name

dye depot

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/dye-depot

### Minecraft version

1.20.1 (LTS)

### Describe the bug

Crashes on launch

### Steps to reproduce

1.Put dye depot version 1.03 for fabic in mod folder 
2. launch
3. crash
... Overly simple, I know

Crash repost [crash-2024-10-10_14.23.12-client.txt](https://github.com/user-attachments/files/17328501/crash-2024-10-10_14.23.12-client.txt)

### Logs

https://pastebin.com/NPUr3wn2

### Additional context

Was told to post here

**Comment by veccyboi** [comment]
i had the same issue just recently.
in the crash report, i noticed this part of the stacktrace: ``Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/client/rendereregistry/v1/BlockEntityRendererRegistry
	at com.ninni.dye_depot.registry.DDVanillaIntegration$Client.registerModelLayers(DDVanillaIntegration.java:231) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at com.ninni.dye_depot.registry.DDVanillaIntegration$Client.clientInit(DDVanillaIntegration.java:224) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at com.ninni.dye_depot.DyeDepotClient.onInitializeClient(DyeDepotClient.java:11) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23209!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:46) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23224!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 18 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.client.rendereregistry.v1.BlockEntityRendererRegistry
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
	at com.ninni.dye_depot.registry.DDVanillaIntegration$Client.registerModelLayers(DDVanillaIntegration.java:231) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at com.ninni.dye_depot.registry.DDVanillaIntegration$Client.clientInit(DDVanillaIntegration.java:224) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at com.ninni.dye_depot.DyeDepotClient.onInitializeClient(DyeDepotClient.java:11) ~[dye_depot-1.0.3-fabric_mapped_srg_1.20.1.jar%23500!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.46+1.20.1.jar%23209!/:1.0.0-beta.46+1.20.1] {}
	at org.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:46) ~[Connector-1.0.0-beta.46+1.20.1-mod.jar%23224!/:1.0.0-beta.46+1.20.1] {re:mixin,re:classloading}
	... 18 more``
looking around the fabric api github, it appears as though `net.fabricmc.fabric.api.client.rendereregistry.v1.BlockEntityRendererRegistry` has been deprecated and replaced with `net.fabricmc.fabric.api.client.rendering.v1.BlockEntityRendererRegistry`. i think this may be the source of the issue

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
