### ISSUE TITLE
Polymer dependent mod cannot run correctly

### ISSUE THREAD

**Issue by ASHISK404** [Sinytra/Connector#1476]
### Minecraft version

1.20.1

### Describe the bug

Polymer-dependent mod cannot be server-side only, and after the mod is added to the client, the console prompts an itemgroup error after the player joins the server, and after the player exits, the client cannot be linked unless the server is restarted

### Steps to reproduce

1.server install connector,arbitrary reliance on Polymer mods(such as moretools-1.5.0+1.20.1(https://www.curseforge.com/minecraft/mc-mods/more-tools-polymer),polymer;(I use mohist)
2.start the server and join
3.client prompts that mod is missing
4.the client add moretools mod 
5.try to join again
6.Console eject error:
[Polymer]: Failed to load contents for an ItemGroup
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft
    at
7.quit the server and try to join again
8.Unable to join again, no connection is displayed, and the console has no information

Connector-1.0.0-beta.46+1.20.1.jar,polymer-bundled-0.5.20+1.20.1.jar,moretools-1.5.0+1.20.1.jar

### Logs

https://gist.github.com/ASHISK404/a37b9d38f69ecc9f522acf519d676e64

**Comment by ASHISK404** [comment]
Supplement, this error will also occur when only polymer and connector are added.

[11:56:45 WARN]: Failed to load contents for an ItemGroupjava.lang.NoClassDefFoundError: net/minecraft/client/Minecraft        at fr.iglee42.createcasing.registries.ModCreativeModeTabs$RegistrateDisplayItemsGenerator.m_257865_(ModCreativeModeTabs.java:124) ~[CreateCasing-1.20.1-1.6.1.jar%23370!/:?]        at net.minecraftforge.common.ForgeHooks.onCreativeModeTabBuildContents(ForgeHooks.java:1640) ~[forge-1.20.1-47.3.11-universal.jar%23465!/:?]        at net.minecraft.world.item.CreativeModeTab.m_269498_(CreativeModeTab.java:129) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.world.item.CreativeModeTab.polymer$getContentsWith(CreativeModeTab.java:1544) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:45) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.api.item.PolymerItemGroupUtils.getContentsFor(PolymerItemGroupUtils.java:37) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.impl.networking.packets.PolymerItemGroupContent.of(PolymerItemGroupContent.java:23) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.syncItemGroupContents(PolymerServerProtocol.java:251) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.syncItemGroup(PolymerServerProtocol.java:236) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.sendCreativeSyncPackets(PolymerServerProtocol.java:223) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at eu.pb4.polymer.core.impl.networking.PolymerServerProtocol.sendSyncPackets(PolymerServerProtocol.java:163) ~[polymer-bundled-0.5.20+1.20.1$polymer-core-0.5.20+1.20.1_mapped_srg_1.20.1.jar%23938!/:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.md7cb9a3$polymer_core$lambda$polymerCore$resendLanguage$0$3(ServerGamePacketListenerImpl.java:10628) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.handler$bpn000$polymer_core$polymerCore$resendLanguage(ServerGamePacketListenerImpl.java:10637) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5617_(ServerGamePacketListenerImpl.java:2795) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.network.protocol.game.ServerboundClientInformationPacket.m_5797_(ServerboundClientInformationPacket.java:48) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.network.protocol.game.ServerboundClientInformationPacket.m_5797_(ServerboundClientInformationPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1026) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:176) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:124) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:1009) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:1003) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:112) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:988) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:914) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:286) ~[server-1.20.1-20230612.114412-srg.jar%23460!/:?]        at java.lang.Thread.run(Thread.java:842) [?:?]Caused by: java.la

**Comment by Su5eD** [comment]
As our LTS support target, 1.20.1 now only receives critical fixes related to Connector bugs. Please upgrade to the latest version for mod compatibility support.
