### ISSUE TITLE
Incompatibility with Arcadian Dream

### ISSUE THREAD

**Issue by dasdwavbc** [Sinytra/Connector#1477]
### Mod Name

Arcadian Dream

### Mod Homepage

https://github.com/Maxmani/arcadian-dream

### Minecraft version

1.20.1 (LTS)

### Describe the bug

maybe something in mixin crash the game

### Steps to reproduce

1.add mod sinytra connector , Arcadian Dream latest version and prefix mods
2.minecraft1.20.1 forge 47.3.11
3.
...

### Logs

[1710月2024 21:38:54.209] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Little_Ming, --version, 1.20.1-灵梦的归家（精简版）, --gameDir, E:\BaiduNetdiskDownload\mchxx\.minecraft\versions\1.20.1-灵梦的归家（精简版）, --assetsDir, E:\BaiduNetdiskDownload\mchxx\.minecraft\assets, --assetIndex, 5, --uuid, 2b7ba93b92ac4583aa7f5f91825a8ec7, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 1598, --height, 868, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.11, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412] [1710月2024 21:38:54.214] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.1 by Eclipse Adoptium; OS Windows 10 arch amd64 version 10.0 [1710月2024 21:38:54.385] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow [1710月2024 21:38:54.529] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 [1710月2024 21:38:54.789] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6 [1710月2024 21:38:54.855] [main/INFO] [mixin-transmog/]: Mixin Transmogrifier is definitely up to no good... [1710月2024 21:38:54.877] [main/INFO] [mixin-transmog/]: crimes against java were committed [1710月2024 21:38:54.894] [main/INFO] [mixin-transmog/]: Original mixin transformation service successfully crobbed by mixin-transmogrifier! [1710月2024 21:38:54.931] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/E:/BaiduNetdiskDownload/mchxx/.minecraft/versions/1.20.1-灵梦的归家（精简版）/mods/%5B信雅互联%5D%20Connector-1.0.0-beta.46+1.20.1.jar%23162%23165!/ Service=ModLauncher Env=CLIENT [1710月2024 21:38:55.105] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 565.90, NVIDIA Corporation [1710月2024 21:38:55.259] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\BaiduNetdiskDownload\mchxx\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.11\fmlcore-1.20.1-47.3.11.jar is missing mods.toml file [1710月2024 21:38:55.261] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\BaiduNetdiskDownload\mchxx\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.11\javafmllanguage-1.20.1-47.3.11.jar is missing mods.toml file [1710月2024 21:38:55.263] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\BaiduNetdiskDownload\mchxx\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.11\lowcodelanguage-1.20.1-47.3.11.jar is missing mods.toml file [1710月2024 21:38:55.265] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file E:\BaiduNetdiskDownload\mchxx\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.11\mclanguage-1.20.1-47.3.11.jar is missing mods.toml file [1710月2024 21:38:55.496] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 48 dependencies adding them to mods collection [1710月2024 21:38:55.708] [main/INFO] [org.sinytra.connector.locator.DependencyResolver/]: Dependency resolution found 8 candidates to load [1710月2024 21:38:56.155] [main/INFO] [org.sinytra.connector.service.hacks.ModuleLayerMigrator/]: Successfully made module authlib transformable [1710月2024 21:38:56.592] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [1710月2024 21:38:56.629] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-灵梦的归家（精简版）, --gameDir, E:\BaiduNetdiskDownload\mchxx\.minecraft\versions\1.20.1-灵梦的归家（精简版）, --assetsDir, E:\BaiduNetdiskDownload\mchxx\.minecraft\assets, --uuid, 2b7ba93b92ac4583aa7f5f91825a8ec7, --username, Little_Ming, --assetIndex, 5, --accessToken, ❄❄❄❄❄❄❄❄, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 1598, --height, 868] [1710月2024 21:38:56.756] [main/WARN] [mixin/]: Reference map '' for adapter.init.mixins.json could not be read. If this is a development environment you can ignore this message [1710月2024 21:38:57.733] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5). [1710月2024 21:38:58.936] [pool-4-thread-1/FATAL] [mixin/]: Mixin apply for mod arcadiandream failed arcadiandream.mixins.json:EntityMixin from mod arcadiandream -> net.minecraft.world.entity.Entity: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @ModifyExpressionValue annotation on arcadiandream$preventPushFromFluids could not find any targets matching 'lambda$updateFluidHeightAndDoFluidPushing$26' in net.minecraft.world.entity.Entity. Using refmap arcadiandream-refmap.json [PREINJECT Applicator Phase -> arcadiandream.mixins.json:EntityMixin from mod arcadiandream -> Prepare Injections ->  -> modifyExpressionValue$znb000$arcadiandream$preventPushFromFluids(D)D -> Parse] org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @ModifyExpressionValue annotation on arcadiandream$preventPushFromFluids could not find any targets matching 'lambda$updateFluidHeightAndDoFluidPushing$26' in net.minecraft.world.entity.Entity. Using refmap arcadiandream-refmap.json [PREINJECT Applicator Phase -> arcadiandream.mixins.json:EntityMixin from mod arcadiandream -> Prepare Injections ->  -> modifyExpressionValue$znb000$arcadiandream$preventPushFromFluids(D)D -> Parse] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at com.llamalad7.mixinextras.injector.MixinExtrasInjectionInfo.<init>(MixinExtrasInjectionInfo.java:10) ~[MixinExtras-0.3.5.jar%23271!/:?] 	at com.llamalad7.mixinextras.injector.ModifyExpressionValueInjectionInfo.<init>(ModifyExpressionValueInjectionInfo.java:15) ~[MixinExtras-0.3.5.jar%23271!/:?] 	at jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] 	at net.minecraftforge.registries.GameData.init(GameData.java:107) ~[forge-1.20.1-47.3.11-universal.jar%23177!/:?] 	at net.minecraftforge.registries.GameData.<clinit>(GameData.java:93) ~[forge-1.20.1-47.3.11-universal.jar%23177!/:?] 	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:429) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] 	at net.minecraft.core.registries.BuiltInRegistries.forge(BuiltInRegistries.java:409) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] 	at net.minecraft.core.registries.BuiltInRegistries.<clinit>(BuiltInRegistries.java:121) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] 	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:43) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23172!/:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?] 	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] 	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

### Additional context

I need to make a modpack about danmuku battle,wanting this mod to work on forge.
Also have reported to discord of Arcadian Dream.

**Comment by unilock** [comment]
1. You *must* use Forge 47.1.3 or the latest appropriate version of NeoForge when running Sinytra Connector on 1.20.1.
2. Arcadian Dream requires [Connector Extras](https://modrinth.com/mod/connector-extras).

See here for my exact set of mods to have Arcadian Dream working: https://github.com/Sinytra/Connector/issues/490#issuecomment-1805939092

Things may not work well if you have any Forge mods that depend on GeckoLib. This is a limitation of the environment for 1.20.1; not much can be done about it at this point.
