### ISSUE TITLE
Neoforge server crash

### ISSUE THREAD

**Issue by cogumelodogit** [Sinytra/Connector#1553]
### Minecraft version

1.20.1 (LTS)

### Describe the bug

Server crash on early loading

### Steps to reproduce

1.make a neoforge server
2.install Sinytra Connector, Connector Extras and Forgified Fabric API
3.run the server

### Logs

[13:36:17.944] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.neoForgeVersion, 21.3.41-beta, --fml.fmlVersion, 5.0.6, --fml.mcVersion, 1.21.3, --fml.neoFormVersion, 20241023.131943]  [13:36:17.946] [main/INFO] [Launcher/MODLAUNCHER]: JVM identified as BellSoft OpenJDK 64-Bit Server VM 21.0.5+11-LTS  [13:36:17.947] [main/INFO] [Launcher/MODLAUNCHER]: ModLauncher 11.0.4+main.d2e20e43 starting: java version 21.0.5 by BellSoft; OS Linux arch amd64 version 6.12.1-artix1-1  [13:36:18.133] [main/INFO] [loading.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver  Exception in thread "main" java.util.ServiceConfigurationError: cpw.mods.modlauncher.api.ITransformationService: org.sinytra.connector.service.ConnectorLoaderService Unable to get public no-arg constructor         at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)         at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)         at java.base/java.util.ServiceLoader.loadProvider(ServiceLoader.java:906)         at java.base/java.util.ServiceLoader$LayerLookupIterator.hasNext(ServiceLoader.java:958)         at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1491)         at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:332)         at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)         at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)         at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)         at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)         at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:127)         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:83)         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74)         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)         at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)         at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210)         at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/loading/ImmediateWindowProvider         at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)         at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3549)         at java.base/java.lang.Class.getConstructor0(Class.java:3754)         at java.base/java.lang.Class.getConstructor(Class.java:2442)         at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)         at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)         at java.base/java.security.AccessController.doPrivileged(AccessController.java:571)         at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)         ... 16 more Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fml.loading.ImmediateWindowProvider         at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)         at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)         at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:216)         at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)         ... 24 more

**Comment by samuil6996** [comment]
Any fix? Same issue.
