### ISSUE TITLE
game keeps crashing when loading into minecraft

### ISSUE THREAD

**Issue by WillIFAS** [Sinytra/Connector#22]
### Describe the bug

for some reason when i try to use sinytra, with better nether and better end it crash my game saying error code one

### Steps to reproduce

1. i click play
2. it loads a little bit
3. it crashes with error code 1
...

### Logs

[09Aug2023 17:50:55.527] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, WillC0A1, --version, 1.20.1-forge-47.1.3, --gameDir, C:\Users\dmcne\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dmcne\AppData\Roaming\.minecraft\assets, --assetIndex, 5, --uuid, 3dc898d5a7ec42b3bbd3db42f1b339c8, --accessToken, ????????, --clientId, MTdjMTMxMTAtYmExNC00YWJkLWJlOWMtZTcwMjE2Mzg5Njgw, --xuid, 2535447589783567, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412] [09Aug2023 17:50:55.532] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.3 by Microsoft; OS Windows 10 arch amd64 version 10.0 [09Aug2023 17:50:55.793] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow [09Aug2023 17:50:55.863] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6 [09Aug2023 17:50:55.989] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6 [09Aug2023 17:50:56.096] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/dmcne/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23100!/ Service=ModLauncher Env=CLIENT [09Aug2023 17:50:56.148] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce RTX 3060/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.23, NVIDIA Corporation [09Aug2023 17:50:56.152] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/dmcne/AppData/Roaming/.minecraft/mods/Connector-1.0.0-beta+1.20.1-full.jar%23160!/ Service=ModLauncher Env=CLIENT [09Aug2023 17:50:56.913] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\dmcne\AppData\Roaming\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.1.3\fmlcore-1.20.1-47.1.3.jar is missing mods.toml file [09Aug2023 17:50:56.918] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\dmcne\AppData\Roaming\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.1.3\javafmllanguage-1.20.1-47.1.3.jar is missing mods.toml file [09Aug2023 17:50:56.923] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\dmcne\AppData\Roaming\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.1.3\lowcodelanguage-1.20.1-47.1.3.jar is missing mods.toml file [09Aug2023 17:50:56.928] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\dmcne\AppData\Roaming\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.1.3\mclanguage-1.20.1-47.1.3.jar is missing mods.toml file [09Aug2023 17:50:57.197] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 41 dependencies adding them to mods collection [09Aug2023 17:51:05.167] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [09Aug2023 17:51:05.282] [main/INFO] [mixin/]: Compatibility level set to JAVA_17 [09Aug2023 17:51:05.740] [main/ERROR] [mixin/]: bclib.mixins.client-bIvPV.json:AnvilScreenMixin from mod (unknown): method_25402 does not exist in target interface net.minecraft.client.gui.components.events.ContainerEventHandler org.spongepowered.reloc.asm.mixin.transformer.throwables.InvalidMixinException: method_25402 does not exist in target interface net.minecraft.client.gui.components.events.ContainerEventHandler 	at org.spongepowered.reloc.asm.mixin.transformer.InterfaceInfo.renameMethod(InterfaceInfo.java:188) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinPreProcessorStandard.prepareSoftImplements(MixinPreProcessorStandard.java:234) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinPreProcessorStandard.prepareMethod(MixinPreProcessorStandard.java:215) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinPreProcessorStandard.prepare(MixinPreProcessorStandard.java:184) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinInfo$State.validateChanges(MixinInfo.java:443) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinInfo$State.validate(MixinInfo.java:343) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinInfo.validate(MixinInfo.java:914) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinConfig.postInitialise(MixinConfig.java:803) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:568) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at dev.su5ed.sinytra.connector.service.ConnectorMixinLaunchPlugin.processClass(ConnectorMixinLaunchPlugin.java:28) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at java.lang.Class.forName0(Native Method) ~[?:?] 	at java.lang.Class.forName(Class.java:467) ~[?:?] 	at org.spongepowered.asm.service.modlauncher.ModLauncherClassProvider.findClass(ModLauncherClassProvider.java:76) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:96) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:706) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at dev.su5ed.sinytra.connector.service.ConnectorPreLaunchPlugin.initializeLaunch(ConnectorPreLaunchPlugin.java:30) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$11(LaunchPluginHandler.java:100) ~[modlauncher-10.0.9.jar:?] 	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?] 	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:100) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:51) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] [09Aug2023 17:51:06.253] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-forge-47.1.3, --gameDir, C:\Users\dmcne\AppData\Roaming\.minecraft, --assetsDir, C:\Users\dmcne\AppData\Roaming\.minecraft\assets, --uuid, 3dc898d5a7ec42b3bbd3db42f1b339c8, --username, WillC0A1, --assetIndex, 5, --accessToken, ????????, --clientId, MTdjMTMxMTAtYmExNC00YWJkLWJlOWMtZTcwMjE2Mzg5Njgw, --xuid, 2535447589783567, --userType, msa, --versionType, release] [09Aug2023 17:51:08.589] [pool-5-thread-1/FATAL] [mixin/]: Mixin apply for mod (unknown) failed bclib.mixins.common-RayVs.json:AnvilMenuMixin from mod (unknown) -> net.minecraft.world.inventory.AnvilMenu: org.spongepowered.reloc.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on bcl_onDamageAnvil could not find any targets matching 'm_150476_' in net.minecraft.world.inventory.AnvilMenu. Using refmap bclib-refmap.json [PREINJECT Applicator Phase -> bclib.mixins.common-RayVs.json:AnvilMenuMixin from mod (unknown) -> Prepare Injections ->  -> handler$zcm000$bcl_onDamageAnvil(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/reloc/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] org.spongepowered.reloc.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on bcl_onDamageAnvil could not find any targets matching 'm_150476_' in net.minecraft.world.inventory.AnvilMenu. Using refmap bclib-refmap.json [PREINJECT Applicator Phase -> bclib.mixins.common-RayVs.json:AnvilMenuMixin from mod (unknown) -> Prepare Injections ->  -> handler$zcm000$bcl_onDamageAnvil(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lorg/spongepowered/reloc/asm/mixin/injection/callback/CallbackInfo;)V -> Parse] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at jdk.internal.reflect.GeneratedConstructorAccessor68.newInstance(Unknown Source) ~[?:?] 	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] 	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at org.spongepowered.reloc.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at dev.su5ed.sinytra.connector.service.ConnectorMixinLaunchPlugin.processClass(ConnectorMixinLaunchPlugin.java:28) ~[Connector-1.0.0-beta+1.20.1-full.jar%23160!/:?] 	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30] 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?] 	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] 	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] 	at net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:505) ~[client-1.20.1-20230612.114412-srg.jar%23167!/:?] 	at net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:301) ~[client-1.20.1-20230612.114412-srg.jar%23167!/:?] 	at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46) ~[client-1.20.1-20230612.114412-srg.jar%23167!/:?] 	at net.minecraft.client.main.Main.lambda$main$0(Main.java:151) ~[client-1.20.1-20230612.114412-srg.jar%23167!/:?] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?] 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Su5eD** [comment]
Please try again using Connector version `1.0.0-beta.2+1.20.1` and Forgified Fabric API `0.86.1+1.8.1+1.20.1`.

**Comment by WillIFAS** [comment]
alright i solved it but some of the better end and better nether biomes aren't even spawning in, no grass and stuff

**Comment by WillIFAS** [comment]
> Please try again using these builds:
> 
> * [Forgified Fabric API `0.86.1+1.8.1+1.20.1`](https://modrinth.com/mod/forgified-fabric-api/version/0.86.1+1.8.1+1.20.1)
> * [Connector](https://github.com/Sinytra/Connector/suites/14954200366/artifacts/852775615) - extract `Connector-1.0.0-beta.3+1.20.1-full.jar` from the zip

alright i solved it but some of the better end and better nether biomes aren't even spawning in, no grass and stuff

**Comment by Su5eD** [comment]
Can you try again using Connector beta 5 and the latest Forgified Fabric API? To be sure, please create a new world, too.

**Comment by Su5eD** [comment]
Closing as stale / unable to reproduce
