### ISSUE TITLE
Tech Reborn Crash on Server

### ISSUE THREAD

**Issue by EndangeredNayla** [Sinytra/Connector#250]
### Describe the bug

Tech Reborn Crash on Server

### Steps to reproduce

boot server with tech reborn and connector and forgified fabric

### Logs

https://gist.github.com/EndangeredNayla/5801e750a462190645f0c6bf19174e53

### Additional context

```
et.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:70) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:66) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:67) ~[Connector-1.0.0-beta.14+1.20.1-mod.jar%23494!/:1.0.0-beta.14+1.20.1]
	at net.minecraft.server.Main.handler$ben000$earlyInit(Main.java:1515) ~[server-1.20.1-20230612.114412-srg.jar%23884!/:?]
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23884!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2354!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'techreborn'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:56) ~[Connector-1.0.0-beta.14+1.20.1-mod.jar%23494!/:1.0.0-beta.14+1.20.1]
	... 17 more
	Suppressed: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
		at reborncore.common.config.Configuration.setup(Configuration.java:68) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
		at reborncore.common.config.Configuration.<init>(Configuration.java:52) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
		at reborncore.RebornCore.onInitialize(RebornCore.java:72) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
		at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:56) ~[Connector-1.0.0-beta.14+1.20.1-mod.jar%23494!/:1.0.0-beta.14+1.20.1]
		at net.minecraft.server.Main.handler$ben000$earlyInit(Main.java:1515) ~[server-1.20.1-20230612.114412-srg.jar%23884!/:?]
		at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23884!/:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
		at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
		at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
		at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
		at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
		at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.3.jar%2368!/:?]
		at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2354!/:?]
		at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
		... 23 more
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at reborncore.common.config.Configuration.setup(Configuration.java:68) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
	at reborncore.common.config.Configuration.<init>(Configuration.java:52) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
	at techreborn.TechReborn.onInitialize(TechReborn.java:63) ~[TechReborn-5.8.7_mapped_srg_1.20.1.jar%231530!/:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:56) ~[Connector-1.0.0-beta.14+1.20.1-mod.jar%23494!/:1.0.0-beta.14+1.20.1]
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:137) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at reborncore.common.config.Configuration.setup(Configuration.java:68) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
	at reborncore.common.config.Configuration.<init>(Configuration.java:52) ~[TechReborn-5.8.7$RebornCore-5.8.7_mapped_srg_1.20.1.jar%231525!/:?]
	at techreborn.TechReborn.onInitialize(TechReborn.java:63) ~[TechReborn-5.8.7_mapped_srg_1.20.1.jar%231530!/:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23489!/:1.0.0-beta.14+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:56) ~[Connector-1.0.0-beta.14+1.20.1-mod.jar%23494!/:1.0.0-beta.14+1.20.1]
```

**Comment by EndangeredNayla** [comment]
This works fine client side

**Comment by Su5eD** [comment]
I tested this on a server with only the following mods and it boots fine.
1) Forge 47.1.3
2) Connector-1.0.0-beta.13+1.20.1-full
3) fabric-api-0.88.1+1.9.11+1.20.1
4) TechReborn-5.8.7

**Comment by EndangeredNayla** [comment]
Hmm I'll do some debugging

**Comment by EndangeredNayla** [comment]
Does this spam your console?

Caused by: java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtil

**Comment by Su5eD** [comment]
Nope, there is no such error. Try running a clean instance with only the mods I mentioned

**Comment by EndangeredNayla** [comment]
is it just standard forge 47.1.3 libraries or do i need fabric libaries in the folder aswell?

**Comment by Su5eD** [comment]
Just install Forge 47.1.3

**Comment by Su5eD** [comment]
Closing as stale / cannot reproduce
