### ISSUE TITLE
Incompat with Modernfix

### ISSUE THREAD

**Issue by Xplodin** [Sinytra/Connector#276]
### Mod Name

Modernfix

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/modernfix

### Describe the bug

crash due to memory leak patch failing from modernfix

### Steps to reproduce

1. update connector to latest
2. delete .connector folder in mods
3. crash on launch sometimes freeze 
...

### Logs

https://gist.github.com/Xplodin/79dbb4b2a5f6e9d5ade505c22a99c686

### Additional context

Failed to patch mixin memory leak
java.lang.NoSuchFieldException: NO_GROUP
	at java.lang.Class.getDeclaredField(Class.java:2610) ~[?:?]
	at org.embeddedt.modernfix.platform.forge.ModernFixPlatformHooksImpl.injectPlatformSpecificHacks(ModernFixPlatformHooksImpl.java:106) ~[modernfix-forge-5.7.2+mc1.20.1.jar%23705!/:5.7.2+mc1.20.1]
	at org.embeddedt.modernfix.core.ModernFixMixinPlugin.<init>(ModernFixMixinPlugin.java:71) ~[modernfix-forge-5.7.2+mc1.20.1.jar%23705!/:5.7.2+mc1.20.1]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.PluginHandle.<init>(PluginHandle.java:97) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinConfig.onSelect(MixinConfig.java:708) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.selectConfigs(MixinProcessor.java:498) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:460) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at io.github.steelwoolmc.shadow.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[Connector-1.0.0-beta.14+1.20.1-full.jar%23485!/:1.0.0-beta.14+1.20.1]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:637) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$18(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.3.jar:1.0]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]

**Comment by EndangeredNayla** [comment]
Thats not the crash please post the full debug.log

**Comment by Xplodin** [comment]
> Thats not the crash please post the full debug.log

full debug is in the logs log

**Comment by Xplodin** [comment]
sorry all, its compatible.
For some reason it took 5m more to load than it normally does
