### ISSUE TITLE
Modern Beta crash do to sky Color

### ISSUE THREAD

**Issue by No1129** [Sinytra/Connector#30]
### Mod Name

Modern Beta

### Mod Homepage

https://github.com/b3spectacled/modern-beta-fabric

### Describe the bug

Crash mid mixin mixing

### Steps to reproduce

load game with modern beta loaded

### Logs

https://file.garden/Yjp9XGA2LRQTk7Ha/debug8102023.log

### Additional context

Exception:
```
Exception caught from launcher
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 8 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.1.3/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 15 more
Caused by: org.spongepowered.reloc.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/dev.su5ed.sinytra.connector.service.ConnectorMixinLaunchPlugin.processClass(ConnectorMixinLaunchPlugin.java:28)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.RenderStateShard.<clinit>(RenderStateShard.java:126)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.handler$zpe000$loadClientClasses(Bootstrap.java:1020)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.Bootstrap.m_135889_(Bootstrap.java)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:152)
	... 23 more
Caused by: org.spongepowered.reloc.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method injectSkyColor(Lnet/minecraft/world/phys/Vec3;)Lnet/minecraft/world/phys/Vec3; in modern_beta.mixins-cZQRL.json:client.MixinClientWorld from mod (unknown) failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap modern-beta-fabric-refmap.json
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at LAYER SERVICE/Connector.beta._3._1._20._1.full@1.0.0-beta.3+1.20.1-full/org.spongepowered.reloc.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 41 more
Exiting with ERROR
Process exited with code 2.
```

**Comment by Su5eD** [comment]
The mod appears to work fine on its own; I suppose a forge mod modifies the method in question and breaks the mixin. Can you try locating the mod that causes the conflict? (e.g. using binary search or another preferred method)

**Comment by No1129** [comment]
it was rubidium

**Comment by Su5eD** [comment]
Okay, I'm closing this then given that modern beta itself works, and we're already tracking the rubidium crashes in
- #39

**Comment by FinxdMC** [comment]
it appears that beta.12 has this same problem without rubidium, i tried both, beta.11 and beta.12
beta 11 didn't crash but beta.12 did, and the log gave the exact same error.

the only mods i used were:
- cloth config 11.1.106 fabric (fabric version cause modern beta doesn't recognize the forge one)
- modern beta fabric 6.4.1+1.20
- forgified fabric api 0.87.0+1.9.9+1.20.1
- connector 1.0.0-beta.12+1.20.1-full

launcher log:
[exception.txt](https://github.com/Sinytra/Connector/files/12538205/exception.txt)

debug log:
[debug.log](https://github.com/Sinytra/Connector/files/12538209/debug.log)

seems to be the same or a similar sky colour issue

**Comment by Su5eD** [comment]
Seems like the parameter comparator in adapter broke, but fortunately it's a simple fix.
