### ISSUE TITLE
Crash when punching blocks

### ISSUE THREAD

**Issue by drakray** [Sinytra/Connector#316]
### Describe the bug

Crash to desktop when punchin/mining blocks, after adding:
DramaticDoors 3.0.2
SinytraConnector 1.0.0 beta15
ConnectorExtra 1.1.0
ForgifiedFabricAPI 0.89.0-1.9.17

to personal modPack

### Steps to reproduce

1.Add mods to modpack
2.Load game
3.Punch block
4.Crash
...

### Logs

https://pastebin.com/Kk9CNQBE

### Additional context

<details>

<summary>Crash excerpt</summary>

```
Description: Unexpected error

io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[00-connector-1.0.0-beta.15-1.20.1-full.jar%23348!/:1.0.0-beta.15+1.20.1] {}
	at io.github.steelwoolmc.shadow.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[00-connector-1.0.0-beta.15-1.20.1-full.jar%23348!/:1.0.0-beta.15+1.20.1] {}
	at io.github.steelwoolmc.shadow.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[00-connector-1.0.0-beta.15-1.20.1-full.jar%23348!/:1.0.0-beta.15+1.20.1] {}
	at io.github.steelwoolmc.shadow.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[00-connector-1.0.0-beta.15-1.20.1-full.jar%23348!/:1.0.0-beta.15+1.20.1] {}

```
</details>

Minecraft 1.20.1
NeoForge 47.1.77
Lots of mods, listed in crashReport

**Comment by Lolothepro** [comment]
neoforge is not supported

**Comment by Su5eD** [comment]
> Redirector redirectGetFacing(FFF)Lnet/minecraft/core/Direction; in fabric-renderer-api-v1.mixins.json:client.OverlayVertexConsumerMixin

Yeah, this error occurs when using neoforge. Please use Forge 47.1.3 instead, as explained in #42

**Comment by drakray** [comment]
Ok I see thank you
