### ISSUE TITLE
Auction House crash

### ISSUE THREAD

**Issue by DonorKrovi** [Sinytra/Connector#425]
### Mod Name

auctionhouse

### Mod Homepage

https://modrinth.com/mod/auctionhouse/versions?__cf_chl_tk=rU6TLMuXWL7amwrhpxmtz3p3PJ4tEujnNdfWWOzqcDQ-1698074565-0-gaNycGzNDhA

### Describe the bug

Crash server for startup

### Steps to reproduce

Put and start server

### Logs

https://mclo.gs/rvPQqja

**Comment by Su5eD** [comment]
Will be fixed in beta 21

**Comment by DonorKrovi** [comment]
> Will be fixed in beta 21

No, https://mclo.gs/584BK58

**Comment by Su5eD** [comment]
> eights_economy_p

You haven't listed you were running other mods as well?

**Comment by DonorKrovi** [comment]
> > eights_economy_p
> 
> You haven't listed you were running other mods as well?

This mod requires another one, but the author forgot to include a link to it, however, it is in his GitHub mod
![image](https://github.com/Sinytra/Connector/assets/60231586/87f6bcc9-9956-4c4e-a535-5165c806af38)

**Comment by Su5eD** [comment]
Looks like FFAPI is missing the deprecated command api v1. Should be an easy fix

**Comment by DonorKrovi** [comment]
thanks

**Comment by DonorKrovi** [comment]
https://mclo.gs/QC8ZZ8E

**Comment by DonorKrovi** [comment]
![image](https://github.com/Sinytra/Connector/assets/60231586/0e1beeee-0525-47d0-9e22-87968f43965f)

**Comment by Su5eD** [comment]
> Caused by: java.sql.SQLException: No suitable driver found for jdbc:sqlite:auctionhouse.db
            at java.sql.DriverManager.getConnection(DriverManager.java:706) ~[java.sql:?] {}
            at java.sql.DriverManager.getConnection(DriverManager.java:252) ~[java.sql:?] {}

This sounds like a java SQL connection issue. Does the mod work for you locally?

**Comment by DonorKrovi** [comment]
I'll give it a try now

**Comment by DonorKrovi** [comment]
I ran a local server on Forge and on Fabric

Forge: https://mclo.gs/aPb3oYo
Fabric: https://pastebin.com/mgwKbAKy

It seems to be something on the mod side, I'll try using the version below and explore **GitHub**

**Comment by DonorKrovi** [comment]
Ok, i'm update mod and start server, console more flood https://pastebin.com/6vSCiKNx

**Comment by Su5eD** [comment]
Oh, right. The mod includes an outdated version of polymer which is not compatible with Connector. You need to manually install the [latest release](https://modrinth.com/mod/polymer/version/0.5.17+1.20.1).

**Comment by DonorKrovi** [comment]
Amazingly it works! Thank you!
![image](https://github.com/Sinytra/Connector/assets/60231586/08c253fa-8d0c-4cd4-b5e1-335ad979bcc9)
