### ISSUE TITLE
clientcommands not compatible

### ISSUE THREAD

**Issue by SpraAng** [Sinytra/Connector#441]
### Mod Name

clientcommands

### Mod Homepage

https://modrinth.com/mod/client-commands

### Describe the bug

fail loading

### Steps to reproduce

1.add mod
2.start game
3.Error
...

### Logs

hereinafter

### Additional context

[2710月2023 00:49:30.675] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, _Spr1ng, --version, 1.20.1-Forge_47.1.3, --gameDir, C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3, --assetsDir, C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\assets, --assetIndex, 5, --uuid, 5617d8c214634d879964b29045576405, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}, --launchTarget, forgeclient, --fml.forgeVersion, 47.1.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412]
[2710月2023 00:49:30.680] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.2 by Microsoft; OS Windows 10 arch amd64 version 10.0
[2710月2023 00:49:31.813] [main/INFO] [net.minecraftforge.fml.loading.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[2710月2023 00:49:31.986] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[2710月2023 00:49:32.166] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[2710月2023 00:49:32.447] [main/INFO] [mixin-transmog/]: Mixin Transmogrifier is definitely up to no good...
[2710月2023 00:49:32.491] [main/INFO] [mixin-transmog/]: crimes against java were committed
[2710月2023 00:49:32.525] [main/INFO] [mixin-transmog/]: Original mixin transformation service successfully crobbed by mixin-transmogrifier!
[2710月2023 00:49:32.642] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/1/Desktop/%5B1.18.1%5D%20Trsnk/.minecraft/versions/1.20.1-Forge_47.1.3/mods/Connector-1.0.0-beta.21+1.20.1-full.jar%23186%23189!/ Service=ModLauncher Env=CLIENT
[2710月2023 00:49:32.775] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 527.37, NVIDIA Corporation
[2710月2023 00:49:33.610] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\libraries\net\minecraftforge\fmlcore\1.20.1-47.1.3\fmlcore-1.20.1-47.1.3.jar is missing mods.toml file
[2710月2023 00:49:33.615] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.1.3\javafmllanguage-1.20.1-47.1.3.jar is missing mods.toml file
[2710月2023 00:49:33.620] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.1.3\lowcodelanguage-1.20.1-47.1.3.jar is missing mods.toml file
[2710月2023 00:49:33.625] [main/WARN] [net.minecraftforge.fml.loading.moddiscovery.ModFileParser/LOADING]: Mod file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\libraries\net\minecraftforge\mclanguage\1.20.1-47.1.3\mclanguage-1.20.1-47.1.3.jar is missing mods.toml file
[2710月2023 00:49:34.002] [main/INFO] [net.minecraftforge.fml.loading.moddiscovery.JarInJarDependencyLocator/]: Found 46 dependencies adding them to mods collection
[2710月2023 00:49:35.023] [main/INFO] [dev.su5ed.sinytra.connector.locator.DependencyResolver/]: Dependency resolution found 13 candidates to load
[2710月2023 00:49:37.780] [pool-3-thread-2/WARN] [dev.su5ed.sinytra.connector.transformer.RefmapRemapper/]: Refmap remapper could not find refmap file clientarguments-refmap.json
[2710月2023 00:49:37.780] [pool-3-thread-1/WARN] [dev.su5ed.sinytra.connector.transformer.RefmapRemapper/]: Refmap remapper could not find refmap file client-betterconfig-refmap.json
[2710月2023 00:49:37.781] [pool-3-thread-1/WARN] [dev.su5ed.sinytra.connector.transformer.RefmapRemapper/]: Refmap remapper could not find refmap file betterconfig-refmap.json
[2710月2023 00:49:41.754] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_math in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_math-ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.758] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_terrain in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_terrain-b4246cbd5880c4f8745ccb90e1b102bde3448126_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.779] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_core in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_core-d64d5f90be66300da41ef58f4f1736db2499784f_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.786] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_reversal in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_reversal-ca64c0890c106f1a2207623c316fce86f250b918_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.806] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_reversal in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_reversal-ca64c0890c106f1a2207623c316fce86f250b918_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.807] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_terrain in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_terrain-b4246cbd5880c4f8745ccb90e1b102bde3448126_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.826] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_math in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_math-ffd2edcfcc0d18147549c88cc7d8ec6cf21b5b91_mapped_srg_1.20.1.jar
[2710月2023 00:49:41.837] [main/WARN] [dev.su5ed.sinytra.connector.locator.ConnectorModMetadataParser/]: Ignoring invalid version for mod com_seedfinding_mc_core in file C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3\mods\.connector\seedcrackerX-2.14.4$mc_core-d64d5f90be66300da41ef58f4f1736db2499784f_mapped_srg_1.20.1.jar
[2710月2023 00:49:43.830] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[2710月2023 00:49:44.124] [main/INFO] [mixin/]: Successfully loaded Mixin Connector [baritone.launch.BaritoneMixinConnector]
[2710月2023 00:49:44.136] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1-Forge_47.1.3, --gameDir, C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\versions\1.20.1-Forge_47.1.3, --assetsDir, C:\Users\1\Desktop\[1.18.1] Trsnk\.minecraft\assets, --uuid, 5617d8c214634d879964b29045576405, --username, _Spr1ng, --assetIndex, 5, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, msa, --versionType, PCL, --width, 854, --height, 480, --quickPlayPath, ${quickPlayPath}]
[2710月2023 00:49:44.170] [main/WARN] [mixin/]: Reference map 'client-betterconfig-refmap.json' for betterconfig.mixins.client.json could not be read. If this is a development environment you can ignore this message
[2710月2023 00:49:44.174] [main/WARN] [mixin/]: Reference map 'betterconfig-refmap.json' for betterconfig.mixins.json could not be read. If this is a development environment you can ignore this message
[2710月2023 00:49:44.203] [main/WARN] [mixin/]: Reference map 'clientarguments-refmap.json' for clientarguments.mixins.json could not be read. If this is a development environment you can ignore this message
[2710月2023 00:49:45.909] [main/ERROR] [net.minecraftforge.coremod.transformer.CoreModBaseTransformer/COREMOD]: Error occurred applying transform of coremod coremods/field_to_method.js function biome
java.lang.IllegalStateException: Field f_47437_ is not private and an instance field
	at net.minecraftforge.coremod.api.ASMAPI.redirectFieldToMethod(ASMAPI.java:260) ~[coremods-5.0.1.jar:?]
	at org.openjdk.nashorn.internal.scripts.Script$Recompilation$120$292A$\^eval\_.initializeCoreMod#transformer(<eval>:11) ~[?:?]
	at org.openjdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:648) ~[nashorn-core-15.3.jar:?]
	at org.openjdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:513) ~[nashorn-core-15.3.jar:?]
	at org.openjdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:520) ~[nashorn-core-15.3.jar:?]
	at org.openjdk.nashorn.api.scripting.ScriptObjectMirror.call(ScriptObjectMirror.java:111) ~[nashorn-core-15.3.jar:?]
	at net.minecraftforge.coremod.NashornFactory.lambda$getFunction$0(NashornFactory.java:18) ~[coremods-5.0.1.jar:5.0.1+15+master.dc5a2922]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:18) ~[coremods-5.0.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModClassTransformer.runCoremod(CoreModClassTransformer.java:10) ~[coremods-5.0.1.jar:?]
	at net.minecraftforge.coremod.transformer.CoreModBaseTransformer.transform(CoreModBaseTransformer.java:38) ~[coremods-5.0.1.jar:?]
	at cpw.mods.modlauncher.TransformerHolder.transform(TransformerHolder.java:41) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.performVote(ClassTransformer.java:179) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:117) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.getMaybeTransformedClassBytes(ModuleClassLoader.java:250) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.buildTransformedClassNodeFor(TransformingClassLoader.java:58) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$10(LaunchPluginHandler.java:100) ~[modlauncher-10.0.9.jar:?]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:222) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.getClassNode(MixinLaunchPluginLegacy.java:207) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.ClassInfo.forName(ClassInfo.java:2022) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.getTargetClass(MixinInfo.java:1018) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readTargetClasses(MixinInfo.java:1008) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.parseTargets(MixinInfo.java:896) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:869) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156) ~[modlauncher-10.0.9.jar:10.0.9+10.0.9+main.dcd20f30]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:632) ~[?:?]
	at java.lang.Class.forName(Class.java:545) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.lambda$updateModuleReads$18(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.3.jar:1.0]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.earlydisplay.DisplayWindow.updateModuleReads(DisplayWindow.java:586) ~[fmlearlydisplay-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.ImmediateWindowHandler.acceptGameLayer(ImmediateWindowHandler.java:71) ~[fmlloader-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.FMLLoader.beforeStart(FMLLoader.java:207) ~[fmlloader-1.20.1-47.1.3.jar:1.0]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.launchService(CommonLaunchHandler.java:92) ~[fmlloader-1.20.1-47.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:60) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:53) ~[?:?]
[2710月2023 00:49:46.376] [main/WARN] [IMixinConfigPlugin/]: Inventory Profiles Next: Doing our own dependency resolving! Because Forge is being Forge....: https://github.com/MinecraftForge/MinecraftForge/issues/9088
[2710月2023 00:49:46.385] [main/WARN] [mixin/]: Error loading class: de/maxhenkel/easyvillagers/blocks/tileentity/TraderTileentityBase (java.lang.ClassNotFoundException: de.maxhenkel.easyvillagers.blocks.tileentity.TraderTileentityBase)
[2710月2023 00:49:46.386] [main/WARN] [mixin/]: @Mixin target de.maxhenkel.easyvillagers.blocks.tileentity.TraderTileentityBase was not found mixins.ipnext.json:MixinTraderTileEntityBase from mod (unknown)
[2710月2023 00:49:46.507] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Will be applying 3 memory leak fixes!
[2710月2023 00:49:46.507] [main/INFO] [memoryleakfix/]: [MemoryLeakFix] Currently enabled memory leak fixes: [targetEntityLeak, biomeTemperatureLeak, hugeScreenshotLeak]

**Comment by thundercreeper10** [comment]
Really hopes this is fixed in the near future!
