### ISSUE TITLE
Nature's Spirit Crashes on Server, but not Local Client

### ISSUE THREAD

**Issue by Aerioos** [Sinytra/Connector#458]
### Describe the bug

Nature's Spirit crashes on Server, but not Local Client

### Steps to reproduce

1. Install the following mods on a Forge 47.1.3 server
- Forgefied Fabric API
- Connector
- Connector Extras
- Nature's Spirit 1.0.0
- Terrablender (Forge)

2. Run `server.bat`

3. Observe crash

**NOTE**
*The log below does contain other mods, but I've verified it happening with only the mods listed above.*

### Logs

https://pastebin.com/wiXWNZNS

### Additional context
I'd like to note that this error does NOT occur locally when running the mods. I've only run into this issue when trying to run a server. 

Excerpt from the logs can be found below
```[29Oct2023 20:36:53.595] [main/ERROR] [net.minecraft.server.Main/FATAL]: Failed to start the minecraft server
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'natures_spirit'!
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:70) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:66) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:61) ~[Connector-1.0.0-beta.21+1.20.1-mod.jar%23266!/:1.0.0-beta.21+1.20.1]
	at net.minecraft.server.Main.handler$bpm000$connectormod$earlyInit(Main.java:1015) ~[server-1.20.1-20230612.114412-srg.jar%23429!/:?]
	at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23429!/:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.1.3.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.1.3.jar%2369!/:?]
	at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.1.3.jar%2369!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'natures_spirit'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:50) ~[Connector-1.0.0-beta.21+1.20.1-mod.jar%23266!/:1.0.0-beta.21+1.20.1]
	... 15 more
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
	at net.fabricmc.fabric.impl.blockrenderlayer.BlockRenderLayerMapImpl.<clinit>(BlockRenderLayerMapImpl.java:83) ~[fabric-blockrenderlayer-v1-1.1.40+8005d10d77.jar%23550!/:1.1.40+8005d10d77]
	at net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap.<clinit>(BlockRenderLayerMap.java:39) ~[fabric-blockrenderlayer-v1-1.1.40+8005d10d77.jar%23550!/:1.1.40+8005d10d77]
	at net.hibiscus.naturespirit.util.HibiscusRegistryHelper.registerPlantBlock(HibiscusRegistryHelper.java:566) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.hibiscus.naturespirit.registration.HibiscusBlocksAndItems.<clinit>(HibiscusBlocksAndItems.java:31) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.hibiscus.naturespirit.NatureSpirit.onInitialize(NatureSpirit.java:48) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:50) ~[Connector-1.0.0-beta.21+1.20.1-mod.jar%23266!/:1.0.0-beta.21+1.20.1]
	... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/RenderType for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.1.3.jar%2369!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.fabric.impl.blockrenderlayer.BlockRenderLayerMapImpl.<clinit>(BlockRenderLayerMapImpl.java:83) ~[fabric-blockrenderlayer-v1-1.1.40+8005d10d77.jar%23550!/:1.1.40+8005d10d77]
	at net.fabricmc.fabric.api.blockrenderlayer.v1.BlockRenderLayerMap.<clinit>(BlockRenderLayerMap.java:39) ~[fabric-blockrenderlayer-v1-1.1.40+8005d10d77.jar%23550!/:1.1.40+8005d10d77]
	at net.hibiscus.naturespirit.util.HibiscusRegistryHelper.registerPlantBlock(HibiscusRegistryHelper.java:566) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.hibiscus.naturespirit.registration.HibiscusBlocksAndItems.<clinit>(HibiscusBlocksAndItems.java:31) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.hibiscus.naturespirit.NatureSpirit.onInitialize(NatureSpirit.java:48) ~[naturespirit-1.0-1.20.1_mapped_srg_1.20.1.jar%23844!/:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[Connector-1.0.0-beta.21+1.20.1-full.jar%23262!/:1.0.0-beta.21+1.20.1]
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:50) ~[Connector-1.0.0-beta.21+1.20.1-mod.jar%23266!/:1.0.0-beta.21+1.20.1]
	... 15 more

**Comment by Aerioos** [comment]
Issue still persists on today's build of Forgified Fabric API
`0.90.4+1.9.30+1.20.1`

**Comment by Su5eD** [comment]
Updating Nature's Spirit to [1.1.1](https://www.curseforge.com/minecraft/mc-mods/natures-spirit/files/4800825) seems to solve the issue
