### ISSUE TITLE
Bending mod won't work.

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [Sinytra/Connector#727]
### Mod Name

bending (fabric)

### Mod Homepage

https://modrinth.com/plugin/bending

### Minecraft version

1.20.1

### Describe the bug

doesn't boot.

### Steps to reproduce

1. boot minecraft neoforge
2. crash

### Logs

https://gist.github.com/OrdinaryCloverOC/be7433a9486ae89a18c31c69d3bc271a

### Additional context

no other mods aside from no chat reports

**Comment by Su5eD** [comment]
> Caused by: java.lang.UnsupportedOperationException: ResourceBundle.Control not supported in named modules
	at java.util.ResourceBundle.checkNamedModule(ResourceBundle.java:1540) ~[?:?] {}
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:1062) ~[?:?] {}
	at me.moros.bending.common.locale.TranslationManager.loadDefaults(TranslationManager.java:95) ~[bending-fabric-mc1.20.1-3.4.0_mapped_mcp_1.20.1.jar%23356!/:?] {re:classloading}

The mod's non-standard way of managing localization is not compatible with named modules, which are used by Forge. As such, this cannot be fixed on our side.
