### ISSUE TITLE
"Adventure Redefined" Incompatible

### ISSUE THREAD

**Issue by GreatKingKeenan** [Sinytra/Connector#747]
### Mod Name

Adventure Redefined

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/adventure-redefined

### Minecraft version

1.20.1

### Describe the bug

Crash on startup. Unable to detect audio devices.

### Steps to reproduce

1.Launch Minecraft with mod installed
2.Crash after mod loading
...

### Logs

https://gist.github.com/GreatKingKeenan/e812a6285ce0a4b7f15c87053e06a0f7

### Additional context

Mod Author asking for assistance in Discord right now. So, issue might be solved by the time I post this.

**Comment by CircuitLord** [comment]
Just a follow up (dev of the mod) I tried it myself with the latest versions of everything, and got this error personally

```
Exception in thread "BetterMusic Player Thread" java.lang.ExceptionInInitializerError
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.SynthesisFilter.load_d(SynthesisFilter.java:1626)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.SynthesisFilter.<init>(SynthesisFilter.java:75)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.Decoder.initialize(Decoder.java:283)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.Decoder.decodeFrame(Decoder.java:138)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.player.advanced.AdvancedPlayer.decodeFrame(AdvancedPlayer.java:157)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.player.advanced.AdvancedPlayer.play(AdvancedPlayer.java:91)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.player.advanced.AdvancedPlayer.play(AdvancedPlayer.java:72)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/circuitlord.bettermusic.PlayerThread.run(PlayerThread.java:84)
Caused by: java.io.IOException: unable to load resource 'sfd.ser'
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.JavaLayerUtils.deserializeArrayResource(JavaLayerUtils.java:146)
	at TRANSFORMER/adventureredefined@0.1.0-1.20.1/javazoom.jl.decoder.SynthesisFilter.load_d(SynthesisFilter.java:1621)
	... 7 more
```

happy to try anything on my side to get it working o7

**Comment by GreatKingKeenan** [comment]
Issue rearises in Connector Beta 36
