### ISSUE TITLE
bclib server crash

### ISSUE THREAD

**Issue by charliez0** [Sinytra/Connector#750]
### Mod Name

bclib

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/bclib

### Minecraft version

1.20.1

### Describe the bug

cannot start server

### Logs

https://gist.github.com/charliez0/1b02caa2829a12a1e5a4877e6c915e12

**Comment by Su5eD** [comment]
> Loading 208 mods

Plead read the issue template more carefully.

> Before reporting, please ensure that:
> - You've installed a **minimal set of mods** required to reproduce the issue.
    Issues with modpacks and excessive amount of mods will not be accepted, as they take a long time to diagnose.
    Knowing which mods are causing problems allows us to focus on fixing the issue as soon as possible.
    If you're unsure which mods might be at fault, try using binary search - removing half of installed mods
    repeatedly until the faulty mod is found.

**Comment by charliez0** [comment]
Removing all mods and the problem is still exists
```plain
[authlib-injector] [INFO] Logging file: D:\Minecraft\mod\mohist\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.4
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
2024-01-22 18:13:27,237 main WARN Advanced terminal features are not available in this environment
[18:13:27] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.2.20, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[18:13:27] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 21.0.1 by Oracle Corporation; OS Windows 11 arch amd64 version 10.0
[18:13:27] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[18:13:27] [main/INFO] [mixin-transmog/]: Mixin Transmogrifier is definitely up to no good...
[18:13:27] [main/INFO] [mixin-transmog/]: crimes against java were committed
[18:13:27] [main/INFO] [mixin-transmog/]: Original mixin transformation service successfully crobbed by mixin-transmogrifier!
[18:13:27] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/D:/Minecraft/mod/mohist/mods/Connector-1.0.0-beta.33+1.20.1.jar%23104%23107!/ Service=ModLauncher Env=SERVER
[18:13:27] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\Minecraft\mod\mohist\libraries\net\minecraftforge\fmlcore\1.20.1-47.2.20\fmlcore-1.20.1-47.2.20.jar is missing mods.toml file
[18:13:27] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\Minecraft\mod\mohist\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.2.20\javafmllanguage-1.20.1-47.2.20.jar is missing mods.toml file
[18:13:27] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\Minecraft\mod\mohist\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.2.20\lowcodelanguage-1.20.1-47.2.20.jar is missing mods.toml file
[18:13:27] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file D:\Minecraft\mod\mohist\libraries\net\minecraftforge\mclanguage\1.20.1-47.2.20\mclanguage-1.20.1-47.2.20.jar is missing mods.toml file
[18:13:28] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 59 dependencies adding them to mods collection
[18:13:28] [main/INFO] [de.su.si.co.lo.DependencyResolver/]: Dependency resolution found 2 candidates to load
[18:13:29] [main/INFO] [de.su.si.co.se.ha.ModuleLayerMigrator/]: Successfully made module authlib transformable
[18:13:29] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[18:13:30] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[18:13:30] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/MouseHandler for invalid dist DEDICATED_SERVER
[18:13:30] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/MouseHandler (java.lang.RuntimeException: Attempted to load class net/minecraft/client/MouseHandler for invalid dist DEDICATED_SERVER)
[18:13:30] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.MouseHandler was not found fabric-screen-api-v1.mixins.json:MouseMixin from mod fabric_screen_api_v1
[18:13:30] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
[18:13:30] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/gui/screens/Screen (java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER)
[18:13:30] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.gui.screens.Screen was not found fabric-screen-api-v1.mixins.json:ScreenAccessor from mod fabric_screen_api_v1
[18:13:30] [main/INFO] [MixinExtras|Service/]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[18:13:37] [main/INFO] [or.be.wo.to.ut.Logger/]: [bclib] Added Config bclib.generator to auto sync (file hash)
[18:13:37] [main/INFO] [or.be.wo.to.ut.Logger/]: [bclib] Added Config bclib.main to auto sync (content diff)
[18:13:37] [main/INFO] [or.be.wo.to.ut.Logger/]: [bclib] Added Config bclib.biomes to auto sync (file hash)
[18:13:37] [main/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
[18:13:37] [main/ERROR] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'bclib'!
        at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.33+1.20.1-mod.jar%23108!/:1.0.0-beta.33+1.20.1] {re:mixin,re:classloading}
        at net.minecraft.server.Main.handler$zgb000$connectormod$earlyInit(Main.java:1515) ~[server-1.20.1-20230612.114412-srg.jar%23113!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
        at net.minecraft.server.Main.main(Main.java:125) ~[server-1.20.1-20230612.114412-srg.jar%23113!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:mixin:A,pl:connector_pre_launch:A}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bclib'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.33+1.20.1-mod.jar%23108!/:1.0.0-beta.33+1.20.1] {re:mixin,re:classloading}
        ... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/gui/screens/Screen for invalid dist DEDICATED_SERVER
        at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:1.0] {}
        at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?] {}
        at org.betterx.bclib.BCLib.onInitialize(BCLib.java:100) ~[%5BFABRIC%5Dbclib-3.0.14_mapped_srg_1.20.1.jar%23245!/:?] {re:mixin,re:classloading}
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.33+1.20.1.jar%23104!/:1.0.0-beta.33+1.20.1] {}
        at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.33+1.20.1-mod.jar%23108!/:1.0.0-beta.33+1.20.1] {re:mixin,re:classloading}
        ... 15 more
```

**Comment by Su5eD** [comment]
Can you try using [this](https://cdn.discordapp.com/attachments/1193253482363359443/1196015327163711508/Connector-1.0.0-beta.331.20.1dev-g5e34e6c.jar?ex=65bf5192&is=65acdc92&hm=b5555857adb818deefda9ac4b11bd5b8af49bb067039e96276805f313a5fa954&) dev build? I've made it remove all references to client-only classes in the constant pool, so java should no longer try to load them.

**Comment by charliez0** [comment]
Problem resolved. Now BetterNether and BetterEnd can start in the server, thanks!
