### ISSUE TITLE
Dependency override format exception

### ISSUE THREAD

**Issue by cvfdgbdfghb** [Sinytra/Connector#778]
### Minecraft version

1.20.1

### Describe the bug

The mod itself failed to start

### Steps to reproduce

1.
2.
3.
...

### Additional context

The mod itself failed to start
[错误报告-2024-1-27_12.22.48.zip](https://github.com/Sinytra/Connector/files/14071074/-2024-1-27_12.22.48.zip)
![屏幕截图 2024-01-27 121520](https://github.com/Sinytra/Connector/assets/157867224/a9f2c35e-e6c5-4c1e-9a8a-e0e88bfbc792)

**Comment by Su5eD** [comment]
> Caused by: net.fabricmc.loader.impl.FormattedException: Failed to parse D:\.minecraft\versions\丝绸生存\config\fabric_loader_dependencies.json
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:59) ~[Connector-1.0.0-beta.34+1.20.1.jar%23273!/:1.0.0-beta.34+1.20.1]
	at net.fabricmc.loader.impl.metadata.DependencyOverrides.<init>(DependencyOverrides.java:56) ~[Connector-1.0.0-beta.34+1.20.1.jar%23273!/:1.0.0-beta.34+1.20.1]
	at dev.su5ed.sinytra.connector.locator.DependencyResolver.<clinit>(DependencyResolver.java:46) ~[Connector-1.0.0-beta.34+1.20.1.jar%23273!/:1.0.0-beta.34+1.20.1]
