### ISSUE TITLE
worldgen/biome bug during game initializing

### ISSUE THREAD

**Issue by Galaxy2K99** [Sinytra/Connector#801]
### Minecraft version

1.20.1

### Describe the bug

during the final stages of launching the game; "minecraft:worldgen/biome" initiates a crash

### Steps to reproduce

1. Create a forge 1.20.1 instance
2. Install sinytra connector and extras
3. Install the following mods (waystones, terralith, tectonic, Little tiles, lazurite, entityculling, embeddium, CreativeCore, better end, better nether, bclib, balm
4. install axiom

### Logs

https://gist.github.com/AvaloriaSinytra/d251a2f7054db9ac8aae118e7354b185

**Comment by Lolothepro** [comment]
Caused by axiom

```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [axiom.mixins.json:render.MixinLevelRendererWithoutSodium from mod axiom] from phase [DEFAULT] in config [axiom.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 30 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @At("INVOKE") on net/minecraft/client/renderer/LevelRenderer::renderChunkLayer_checkEmpty with priority 1000 cannot inject into net/minecraft/client/renderer/LevelRenderer::m_172993_(Lnet/minecraft/client/renderer/RenderType;Lcom/mojang/blaze3d/vertex/PoseStack;DDDLorg/joml/Matrix4f;)V merged by me.jellysquid.mods.sodium.mixin.core.render.world.WorldRendererMixin with priority 1000 [PREINJECT Applicator Phase -> axiom.mixins.json:render.MixinLevelRendererWithoutSodium from mod axiom -> Prepare Injections ->  -> redirect$big000$axiom$renderChunkLayer_checkEmpty(Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$RenderChunk;)Lnet/minecraft/client/renderer/chunk/ChunkRenderDispatcher$CompiledChunk; -> Prepare]
	at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1337) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 30 more
```

**Comment by Su5eD** [comment]
This is a conflict between axiom and embeddium. It's a matter of changing mixin priorities, so it can be fixed easily, but it's up to the mods' authors and lies outside our control.

**Comment by weeeedddd** [comment]
so its for now not possible to use the mod terralith , tectonic?

**Comment by embeddedt** [comment]
@Su5eD The mixin on Axiom's end is called `MixinLevelRendererWithoutSodium`, are you sure this isn't an issue with Axiom failing to detect a Sodium-like mod (e.g. missing alias)?
