### ISSUE TITLE
Extra Alchemy crashes when Pehkui is installed

### ISSUE THREAD

**Issue by Learwin** [Sinytra/Connector#829]
### Mod Name

Extra Alchemy

### Mod Homepage

https://modrinth.com/mod/extraalchemy

### Minecraft version

1.20.1

### Describe the bug

Installing Extra Alchemy works without issue. Installing the forge version of Pehkui also works without issue but as soon as Extra Alchemy and Pehkui are installed together the game crashes.

### Steps to reproduce

1.Install Extra alchemy and pehkui together
2.Launch game
3.Observe the game crashing

### Logs

https://gist.github.com/Learwin/ed86c92b401875e1448a8e4c2fc898bd

### Additional context

- Connector beta 36
- Connector extras 1.9.2
- extra alchemy 1.10.0
- fabric-api 0.91.0 1.10.8
- pehkui 3.7.12

I personally think that this is caused by Extra alchemy's compat with Pehkui. Which specifically requires the Fabric version of Pehkui

```
Caused by: java.lang.NoSuchMethodError: 'net.fabricmc.fabric.api.event.Event virtuoel.pehkui.api.ScaleType.getScaleChangedEvent()'
	at zabi.minecraft.extraalchemy.compat.pehkui.ModSizeModifiers.registerModifiers(ModSizeModifiers.java:32) ~[extraalchemy-fabric-1.20.1-1.10.0_mapped_srg_1.20.1.jar%231261!/:?] {re:classloading}
	at zabi.minecraft.extraalchemy.compat.pehkui.PehkuiCompatBridge.init(PehkuiCompatBridge.java:18) ~[extraalchemy-fabric-1.20.1-1.10.0_mapped_srg_1.20.1.jar%231261!/:?] {re:classloading}
	at zabi.minecraft.extraalchemy.ExtraAlchemy.onInitialize(ExtraAlchemy.java:38) ~[extraalchemy-fabric-1.20.1-1.10.0_mapped_srg_1.20.1.jar%231261!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23376!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23380!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 26 more
```

**Comment by RoomAlex68** [comment]
Use Forge version of Pehkui

**Comment by Learwin** [comment]
> Use Forge version of Pehkui

I am using the forge version of pehkui. Which I said is probably the reason why extra alchemy crashes. As it's looking for a class that does not exist in the forge version of pehkui.

**Comment by Liamgrayskull** [comment]
Can replicate this issue on my end as well, only occurs with Extra Alchemy due to its integration through shrinking/growth potions

**Comment by coco875** [comment]
So logically it's just connector extra who need to make this missing bridge

**Comment by Su5eD** [comment]
Fixed by https://github.com/Sinytra/ConnectorExtras/commit/9a9680e55a46e0cbcd93e4d86f9ed6122a8b5b01 in [ConnectorExtras 1.10.0](https://modrinth.com/mod/connector-extras/version/1.10.0+1.20.1).
