### ISSUE TITLE
the return value of "net.minecraftforge.fml.ModList.get()" is null

### ISSUE THREAD

**Issue by charliez0** [Sinytra/Connector#860]
### Minecraft version

1.20.1

### Describe the bug

the return value of "net.minecraftforge.fml.ModList.get()" is null

### Steps to reproduce

```plain
net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'yuushya'!
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createLoadingException(ConnectorEarlyLoader.java:81) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.loader.ConnectorEarlyLoader.createGenericLoadingException(ConnectorEarlyLoader.java:77) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:55) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23379!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.handler$ekh001$connectormod$earlyInit(Minecraft.java:19423) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:424) ~[client-1.20.1-20230612.114412-srg.jar%23596!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick_render_call,xf:fml:imblocker:window_focus_asm,xf:fml:xaerominimap:xaero_minecraftclient,xf:fml:xaeroworldmap:xaero_wm_minecraftclient,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:182) ~[1.20.1.jar:?] {re:mixin,pl:connector_pre_launch:A,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:flywheel.mixins.json:ClientMainMixin from mod flywheel,pl:mixin:A,pl:connector_pre_launch:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:580) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.20.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'yuushya'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$0(FabricLoaderImpl.java:131) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:129) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23379!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 16 more
Caused by: java.lang.ExceptionInInitializerError
	at com.yuushya.Yuushya.init(Yuushya.java:19) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at com.yuushya.fabriclike.YuushyaFabricLike.init(YuushyaFabricLike.java:7) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at com.yuushya.fabric.YuushyaFabric.onInitialize(YuushyaFabric.java:9) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23379!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 16 more
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraftforge.fml.ModList.getModContainerById(String)" because the return value of "net.minecraftforge.fml.ModList.get()" is null
	at dev.architectury.platform.forge.PlatformImpl$ModImpl.<init>(PlatformImpl.java:95) ~[architectury-9.1.13-forge.jar%23446!/:?] {re:classloading}
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?] {re:mixin}
	at dev.architectury.platform.forge.PlatformImpl.getMod(PlatformImpl.java:72) ~[architectury-9.1.13-forge.jar%23446!/:?] {re:classloading}
	at dev.architectury.platform.Platform.getMod(Platform.java) ~[architectury-9.1.13-forge.jar%23446!/:?] {re:classloading}
	at com.yuushya.registries.YuushyaRegistryConfig.<clinit>(YuushyaRegistryConfig.java:33) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at com.yuushya.Yuushya.init(Yuushya.java:19) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at com.yuushya.fabriclike.YuushyaFabricLike.init(YuushyaFabricLike.java:7) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at com.yuushya.fabric.YuushyaFabric.onInitialize(YuushyaFabric.java:9) ~[%5BFABRIC%5Dyuushya-1.20.1-fabric-2.1.1_mapped_srg_1.20.1.jar%231089!/:?] {re:classloading}
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:127) ~[Connector-1.0.0-beta.36+1.20.1.jar%23374!/:1.0.0-beta.36+1.20.1] {}
	at dev.su5ed.sinytra.connector.mod.ConnectorLoader.load(ConnectorLoader.java:44) ~[Connector-1.0.0-beta.36+1.20.1-mod.jar%23379!/:1.0.0-beta.36+1.20.1] {re:mixin,re:classloading}
	... 16 more
```

**Comment by Su5eD** [comment]
Please use the mod compatibility issue template and provide all necessary information to reproduce this issue, including the mods you're using and a full log
