### ISSUE TITLE
Odd Valkyrien Skies 2 & Create Interactive issue with Connector.

### ISSUE THREAD

**Issue by water-mizuu** [Sinytra/Connector#950]
### Mod Name

Valkyrien Skies 2

### Mod Homepage

https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies

### Minecraft version

1.20.1

### Describe the bug

I have been investigating for a bit, and I admit, I have no clue. It seems to be related to an entity reach mixin. However, the results are inconsistent.

### Steps to reproduce

1. Install a number of mods. In my situation, adding mods when the in-game menu shows 166 mods (with 95 jar files, including connector and VS2) crashes into a mixin error.
2. The game won't launch, stating something about "InvalidInjectionException" to a reach_entity_attributes mod (which I do not have.)

### Logs

[Github Gist](https://gist.github.com/water-mizuu/30bb0729658842cc4dc379865efd9976)

**Comment by Su5eD** [comment]
Install connector extras, which contains a working port of reach entity attributes

**Comment by water-mizuu** [comment]
> Install connector extras, which contains a working port of reach entity attributes

I do have Connector Extras in the modpack, so I presume this should not be closed yet?

**Comment by water-mizuu** [comment]
To clarify, the fatal error says:

```
[29Mar2024 21:57:58.717] [main/FATAL] [mixin/]: Mixin apply for mod reach_entity_attributes failed mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes -> net.minecraft.client.renderer.GameRenderer: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Variable modifier target for net/minecraft/client/renderer/GameRenderer::getActualAttackRange1 was removed by another injector [INJECT Applicator Phase -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes -> Apply Injections ->  -> Inject -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes->@ModifyVariable::getActualAttackRange1(D)D]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/client/renderer/GameRenderer::getActualAttackRange1 was removed by another injector [INJECT Applicator Phase -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes -> Apply Injections ->  -> Inject -> mixins.reach-entity-attributes.json:client.GameRendererMixin from mod reach_entity_attributes->@ModifyVariable::getActualAttackRange1(D)D]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:169) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
       ...
```

This is taken from the gist above.

**Comment by Su5eD** [comment]
> Variable modifier target for net/minecraft/client/renderer/GameRenderer::getActualAttackRange1 was removed by another injector

Looks to be a conflict between REA and another mod's mixin, but the log doesn't point out which one it is

**Comment by Liamgrayskull** [comment]
I'll do some comparison of others who've had the issue along with binary testing to isolate the culprit, it's an interaction of connector extras with what I believe to be a forge mod

**Comment by Corn-on-the-Orb** [comment]
ive got this exact problem, this issue should be taken off of 'closed' as it was never solved in the first place

**Comment by Billnotic** [comment]
I also currently have this issue.

**Comment by Billnotic** [comment]
Ah, it was closed due to it being a Connector Extras issue, not Sinytra Connector. Sorry!

**Comment by Corn-on-the-Orb** [comment]
ah that makes sense my apologies
